/* GANG Software
 * LAB/cmclab/gtk/Controls_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Controls_.H"

namespace cmclab {
namespace gtk {


Controls_::
Controls_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_book
  _main_book_w = new ::gtk::widget1::PopNotebook;
  _main_book_w->set_tab_pos( GTK_POS_TOP );
  _main_book_w->set_title( "CMCLab | Controls" );
  _main_book_w->set( 0 );
  _main_book_w->show();
  set_tooltip( _main_book_w,
    "Controls" );

  // page0
  _page0_w = new ::gtk::widget0::Frame( (char *)0 );
  _page0_w->show();
  _main_book_w->add( _page0_w );

  // vbox2
  _vbox2_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox2_w->show();
  _page0_w->add( _vbox2_w );

  // frame6
  _frame6_w = new ::gtk::widget0::Frame( "potential variable" );
  _frame6_w->show();
  _vbox2_w->add( _frame6_w, false, true, 0 );

  // potential_variable
  _potential_variable_w = new ::gtk::widget0::Entry( 0U );
  _potential_variable_w->set_editable( true );
  _potential_variable_w->show();
  _frame6_w->add( _potential_variable_w );

  // frame7
  _frame7_w = new ::gtk::widget0::Frame( "potential" );
  _frame7_w->show();
  _vbox2_w->add( _frame7_w, true, true, 0 );

  // scrolledwindow5
  _scrolledwindow5_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow5_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow5_w->show();
  _frame7_w->add( _scrolledwindow5_w );

  // potential
  _potential_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _potential_w->set_editable( true );
  _potential_w->show();
  _scrolledwindow5_w->add( _potential_w );

  // label0
  _label0_w = new ::gtk::widget0::Label( "Potential" );
  _label0_w->set_alignment(0, 0.5);
  _label0_w->show();
  _main_book_w->add_label( _label0_w );

  // page1
  _page1_w = new ::gtk::widget0::Frame( (char *)0 );
  _page1_w->show();
  _main_book_w->add( _page1_w );

  // vbox50
  _vbox50_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox50_w->show();
  _page1_w->add( _vbox50_w );

  // frame1
  _frame1_w = new ::gtk::widget0::Frame( "z start" );
  _frame1_w->show();
  _vbox50_w->add( _frame1_w, false, false, 0 );

  // zstart
  _zstart_w = new ::gtk::widget0::Entry( 0U );
  _zstart_w->set_editable( true );
  _zstart_w->show();
  _frame1_w->add( _zstart_w );

  // frame101
  _frame101_w = new ::gtk::widget0::Frame( "dressing" );
  _frame101_w->show();
  _vbox50_w->add( _frame101_w, true, true, 0 );

  // scrolledwindow6
  _scrolledwindow6_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow6_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow6_w->show();
  _frame101_w->add( _scrolledwindow6_w );

  // xstart
  _xstart_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _xstart_w->set_editable( true );
  _xstart_w->show();
  _scrolledwindow6_w->add( _xstart_w );

  // label1
  _label1_w = new ::gtk::widget0::Label( "Initial" );
  _label1_w->set_alignment(0, 0.5);
  _label1_w->show();
  _main_book_w->add_label( _label1_w );

  // parameter_notebook
  _parameter_notebook_w = new ::gtk::widget1::PopNotebookCb<Controls_>(
    this, &Controls_::parameter_notebook_cb );
  _parameter_notebook_w->set_tab_pos( GTK_POS_TOP );
  _parameter_notebook_w->set_title( "CMCLab | Ambient geometry" );
  _parameter_notebook_w->set_blocked( 1 );
  _parameter_notebook_w->show();
  _main_book_w->add( _parameter_notebook_w );
  set_tooltip( _parameter_notebook_w,
    "Ambient geometry" );

  // frame14
  _frame14_w = new ::gtk::widget0::Frame( (char *)0 );
  _frame14_w->show();
  _parameter_notebook_w->add_blocked( _frame14_w );

  // vbox53
  _vbox53_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox53_w->show();
  _frame14_w->add( _vbox53_w );

  // reset_S3
  _reset_S3_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "reset", this, &Controls_::reset_S3_cb );
  _reset_S3_w->show();
  _vbox53_w->add( _reset_S3_w, false, false, 0 );
  set_tooltip( _reset_S3_w,
    "Reset the lambda parameters to their default values" );

  // frame15
  _frame15_w = new ::gtk::widget0::Frame( "lambda1" );
  _frame15_w->show();
  _vbox53_w->add( _frame15_w, false, true, 0 );

  // vbox54
  _vbox54_w = new ::gtk::widget0::VBox( true, 0 );
  _vbox54_w->show();
  _frame15_w->add( _vbox54_w );

  // lambda0_S3
  numberwidget_config const lambda0_S3_param = {
    "lambda", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.0 };

  _lambda0_S3_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &lambda0_S3_param, this, &Controls_::lambda0_S3_cb );

  _lambda0_S3_w->show();
  _vbox54_w->add( _lambda0_S3_w, false, true, 0 );
  set_tooltip( _lambda0_S3_w,
    "Set the loop parameter lambda1 = exp(2 pi i x1), where x1 is the number above." );

  // hbox10
  _hbox10_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox10_w->show();
  _vbox54_w->add( _hbox10_w, true, true, 0 );

  // lambda_button00
  _lambda_button00_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "1", this, &Controls_::lambda_button00_cb );
  _lambda_button00_w->show();
  _hbox10_w->add( _lambda_button00_w, true, true, 0 );
  set_tooltip( _lambda_button00_w,
    "Set lambda1 to 1 (default)" );

  // lambda_button01
  _lambda_button01_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "i", this, &Controls_::lambda_button01_cb );
  _lambda_button01_w->show();
  _hbox10_w->add( _lambda_button01_w, true, true, 0 );
  set_tooltip( _lambda_button01_w,
    "Set lambda1 to i" );

  // lambda_button02
  _lambda_button02_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-1", this, &Controls_::lambda_button02_cb );
  _lambda_button02_w->show();
  _hbox10_w->add( _lambda_button02_w, true, true, 0 );
  set_tooltip( _lambda_button02_w,
    "Set lambda1 to -1" );

  // lambda_button03
  _lambda_button03_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-i", this, &Controls_::lambda_button03_cb );
  _lambda_button03_w->show();
  _hbox10_w->add( _lambda_button03_w, true, true, 0 );
  set_tooltip( _lambda_button03_w,
    "Set lambda1 to -i" );

  // frame16
  _frame16_w = new ::gtk::widget0::Frame( "lambda2" );
  _frame16_w->show();
  _vbox53_w->add( _frame16_w, false, true, 0 );

  // vbox55
  _vbox55_w = new ::gtk::widget0::VBox( true, 0 );
  _vbox55_w->show();
  _frame16_w->add( _vbox55_w );

  // lambda1_S3
  numberwidget_config const lambda1_S3_param = {
    "lambda", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.25 };

  _lambda1_S3_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &lambda1_S3_param, this, &Controls_::lambda1_S3_cb );

  _lambda1_S3_w->show();
  _vbox55_w->add( _lambda1_S3_w, false, true, 0 );
  set_tooltip( _lambda1_S3_w,
    "Set the loop parameter lambda2 = exp(2 pi i x2), where x2 is the number above." );

  // hbox11
  _hbox11_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox11_w->show();
  _vbox55_w->add( _hbox11_w, true, true, 0 );

  // lambda_button10
  _lambda_button10_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "1", this, &Controls_::lambda_button10_cb );
  _lambda_button10_w->show();
  _hbox11_w->add( _lambda_button10_w, true, true, 0 );
  set_tooltip( _lambda_button10_w,
    "Set lambda2 to 1" );

  // lambda_button11
  _lambda_button11_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "i", this, &Controls_::lambda_button11_cb );
  _lambda_button11_w->show();
  _hbox11_w->add( _lambda_button11_w, true, true, 0 );
  set_tooltip( _lambda_button11_w,
    "Set lambda2 to i (default)" );

  // lambda_button12
  _lambda_button12_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-1", this, &Controls_::lambda_button12_cb );
  _lambda_button12_w->show();
  _hbox11_w->add( _lambda_button12_w, true, true, 0 );
  set_tooltip( _lambda_button12_w,
    "Set lambda2 to -1" );

  // lambda_button13
  _lambda_button13_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-i", this, &Controls_::lambda_button13_cb );
  _lambda_button13_w->show();
  _hbox11_w->add( _lambda_button13_w, true, true, 0 );
  set_tooltip( _lambda_button13_w,
    "Set lambda2 to -i" );

  // label1014
  _label1014_w = new ::gtk::widget0::Label( "S3" );
  _label1014_w->set_alignment(0.5, 0.5);
  _label1014_w->show();
  _parameter_notebook_w->add_label( _label1014_w );

  // frame100
  _frame100_w = new ::gtk::widget0::Frame( (char *)0 );
  _frame100_w->show();
  _parameter_notebook_w->add_blocked( _frame100_w );

  // vbox3
  _vbox3_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox3_w->show();
  _frame100_w->add( _vbox3_w );

  // reset_R3
  _reset_R3_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "reset", this, &Controls_::reset_R3_cb );
  _reset_R3_w->show();
  _vbox3_w->add( _reset_R3_w, false, false, 0 );
  set_tooltip( _reset_R3_w,
    "Reset the associate family, normal shift and mean curvature to their default values" );

  // frame3
  _frame3_w = new ::gtk::widget0::Frame( "associate family" );
  _frame3_w->show();
  _vbox3_w->add( _frame3_w, false, true, 0 );

  // vbox4
  _vbox4_w = new ::gtk::widget0::VBox( true, 0 );
  _vbox4_w->show();
  _frame3_w->add( _vbox4_w );

  // lambda_R3
  numberwidget_config const lambda_R3_param = {
    "associate family", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.0 };

  _lambda_R3_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &lambda_R3_param, this, &Controls_::lambda_R3_cb );

  _lambda_R3_w->show();
  _vbox4_w->add( _lambda_R3_w, false, true, 0 );
  set_tooltip( _lambda_R3_w,
    "Move through the associate family of surfaces. The loop parameter is lambda = exp(2 pi i x), where x is the number above." );

  // hbox3
  _hbox3_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox3_w->show();
  _vbox4_w->add( _hbox3_w, true, true, 0 );

  // lambda_button0
  _lambda_button0_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "1", this, &Controls_::lambda_button0_cb );
  _lambda_button0_w->show();
  _hbox3_w->add( _lambda_button0_w, true, true, 0 );
  set_tooltip( _lambda_button0_w,
    "Set the associate family parameter to 1 (default)" );

  // lambda_button1
  _lambda_button1_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "i", this, &Controls_::lambda_button1_cb );
  _lambda_button1_w->show();
  _hbox3_w->add( _lambda_button1_w, true, true, 0 );
  set_tooltip( _lambda_button1_w,
    "Set the associate family parameter to i" );

  // lambda_button2
  _lambda_button2_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-1", this, &Controls_::lambda_button2_cb );
  _lambda_button2_w->show();
  _hbox3_w->add( _lambda_button2_w, true, true, 0 );
  set_tooltip( _lambda_button2_w,
    "Set the associate family parameter to -1" );

  // lambda_button3
  _lambda_button3_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-i", this, &Controls_::lambda_button3_cb );
  _lambda_button3_w->show();
  _hbox3_w->add( _lambda_button3_w, true, true, 0 );
  set_tooltip( _lambda_button3_w,
    "Set the associate family parameter to -i" );

  // frame4
  _frame4_w = new ::gtk::widget0::Frame( "normal shift" );
  _frame4_w->show();
  _vbox3_w->add( _frame4_w, false, true, 0 );

  // vbox5
  _vbox5_w = new ::gtk::widget0::VBox( true, 0 );
  _vbox5_w->show();
  _frame4_w->add( _vbox5_w );

  // normalshift
  numberwidget_config const normalshift_param = {
    "normal shift", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.0 };

  _normalshift_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &normalshift_param, this, &Controls_::normalshift_cb );

  _normalshift_w->show();
  _vbox5_w->add( _normalshift_w, false, true, 0 );
  set_tooltip( _normalshift_w,
    "Move through the normal-shifted family of surfaces" );

  // hbox5
  _hbox5_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox5_w->show();
  _vbox5_w->add( _hbox5_w, true, true, 0 );

  // normalshift_button0
  _normalshift_button0_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "CMC", this, &Controls_::normalshift_button0_cb );
  _normalshift_button0_w->show();
  _hbox5_w->add( _normalshift_button0_w, true, true, 0 );
  set_tooltip( _normalshift_button0_w,
    "Set the normal shift to 1 (default)" );

  // normalshift_button1
  _normalshift_button1_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "K", this, &Controls_::normalshift_button1_cb );
  _normalshift_button1_w->show();
  _hbox5_w->add( _normalshift_button1_w, true, true, 0 );
  set_tooltip( _normalshift_button1_w,
    "Set the normal shift to 0 to produce a K-surface (constant Gaussian curvature)" );

  // normalshift_button2
  _normalshift_button2_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "CMC", this, &Controls_::normalshift_button2_cb );
  _normalshift_button2_w->show();
  _hbox5_w->add( _normalshift_button2_w, true, true, 0 );
  set_tooltip( _normalshift_button2_w,
    "Set the normal shift to -1 to produce the parallel CMC surface" );

  // frame5
  _frame5_w = new ::gtk::widget0::Frame( "mean curvature" );
  _frame5_w->show();
  _vbox3_w->add( _frame5_w, false, true, 0 );

  // mean_curvature
  numberwidget_config const mean_curvature_param = {
    "men curvature", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 1.0 };

  _mean_curvature_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &mean_curvature_param, this, &Controls_::mean_curvature_cb );

  _mean_curvature_w->show();
  _frame5_w->add( _mean_curvature_w );
  set_tooltip( _mean_curvature_w,
    "Set the mean curvature" );

  // label1013
  _label1013_w = new ::gtk::widget0::Label( "R3" );
  _label1013_w->set_alignment(0.5, 0.5);
  _label1013_w->show();
  _parameter_notebook_w->add_label( _label1013_w );

  // frame18
  _frame18_w = new ::gtk::widget0::Frame( (char *)0 );
  _frame18_w->show();
  _parameter_notebook_w->add_blocked( _frame18_w );

  // vbox56
  _vbox56_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox56_w->show();
  _frame18_w->add( _vbox56_w );

  // reset_H3
  _reset_H3_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "reset", this, &Controls_::reset_H3_cb );
  _reset_H3_w->show();
  _vbox56_w->add( _reset_H3_w, false, false, 0 );
  set_tooltip( _reset_H3_w,
    "Reset the loop parameter lambda to its default value" );

  // frame19
  _frame19_w = new ::gtk::widget0::Frame( "Re(lambda)" );
  _frame19_w->show();
  _vbox56_w->add( _frame19_w, false, true, 0 );

  // vbox57
  _vbox57_w = new ::gtk::widget0::VBox( true, 0 );
  _vbox57_w->show();
  _frame19_w->add( _vbox57_w );

  // lambda0_H3
  numberwidget_config const lambda0_H3_param = {
    "lambda", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.8 };

  _lambda0_H3_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &lambda0_H3_param, this, &Controls_::lambda0_H3_cb );

  _lambda0_H3_w->show();
  _vbox57_w->add( _lambda0_H3_w, false, true, 0 );
  set_tooltip( _lambda0_H3_w,
    "Change the real part of the loop parameter lambda" );

  // frame20
  _frame20_w = new ::gtk::widget0::Frame( "Im(lambda)" );
  _frame20_w->show();
  _vbox56_w->add( _frame20_w, false, true, 0 );

  // vbox58
  _vbox58_w = new ::gtk::widget0::VBox( true, 0 );
  _vbox58_w->show();
  _frame20_w->add( _vbox58_w );

  // lambda1_H3
  numberwidget_config const lambda1_H3_param = {
    "lambda", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.0 };

  _lambda1_H3_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &lambda1_H3_param, this, &Controls_::lambda1_H3_cb );

  _lambda1_H3_w->show();
  _vbox58_w->add( _lambda1_H3_w, false, true, 0 );
  set_tooltip( _lambda1_H3_w,
    "Change the imaginary part of the loop parameter lambda" );

  // label1015
  _label1015_w = new ::gtk::widget0::Label( "H3" );
  _label1015_w->set_alignment(0.5, 0.5);
  _label1015_w->show();
  _parameter_notebook_w->add_label( _label1015_w );

  // label2
  _label2_w = new ::gtk::widget0::Label( "Param" );
  _label2_w->set_alignment(0, 0.5);
  _label2_w->show();
  _main_book_w->add_label( _label2_w );

  // page3
  _page3_w = new ::gtk::widget0::Frame( (char *)0 );
  _page3_w->show();
  _main_book_w->add( _page3_w );

  // vbox6
  _vbox6_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox6_w->show();
  _page3_w->add( _vbox6_w );

  // frame8
  _frame8_w = new ::gtk::widget0::Frame( "loop" );
  _frame8_w->show();
  _vbox6_w->add( _frame8_w, false, false, 0 );

  // table1
  _table1_w = new ::gtk::widget0::Table( 1, 2, false );
  _table1_w->show();
  _frame8_w->add( _table1_w );

  // label978
  _label978_w = new ::gtk::widget0::Label( "polylen" );
  _label978_w->set_alignment(0, 0.5);
  _label978_w->show();
  _table1_w->add( _label978_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // polynomial_length
  _polynomial_length_w = new ::gtk::widget0::Entry( 128U );
  _polynomial_length_w->set_editable( true );
  _polynomial_length_w->show();
  _table1_w->add( _polynomial_length_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame9
  _frame9_w = new ::gtk::widget0::Frame( "integration" );
  _frame9_w->show();
  _vbox6_w->add( _frame9_w, false, false, 0 );

  // table2
  _table2_w = new ::gtk::widget0::Table( 2, 2, false );
  _table2_w->show();
  _frame9_w->add( _table2_w );

  // label32
  _label32_w = new ::gtk::widget0::Label( "step" );
  _label32_w->set_alignment(0, 0.5);
  _label32_w->show();
  _table2_w->add( _label32_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label980
  _label980_w = new ::gtk::widget0::Label( "init" );
  _label980_w->set_alignment(0, 0.5);
  _label980_w->show();
  _table2_w->add( _label980_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // initial_integrator_count
  _initial_integrator_count_w = new ::gtk::widget0::Entry( 128U );
  _initial_integrator_count_w->set_editable( true );
  _initial_integrator_count_w->show();
  _table2_w->add( _initial_integrator_count_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // integrator_count
  _integrator_count_w = new ::gtk::widget0::Entry( 128U );
  _integrator_count_w->set_editable( true );
  _integrator_count_w->show();
  _table2_w->add( _integrator_count_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame10
  _frame10_w = new ::gtk::widget0::Frame( (char *)0 );
  _frame10_w->show();
  _vbox6_w->add( _frame10_w, false, false, 0 );

  // frame11
  _frame11_w = new ::gtk::widget0::Frame( "factorization" );
  _frame11_w->show();
  _frame10_w->add( _frame11_w );

  // table3
  _table3_w = new ::gtk::widget0::Table( 4, 2, false );
  _table3_w->show();
  _frame11_w->add( _table3_w );

  // iwasawa_method
  char const *iwasawa_method_labels[] =
    { "faster (Cholesky)", "farther (QR)" };

  _iwasawa_method_w = new ::gtk::widget1::MenuButton(
    0, iwasawa_method_labels, 2 );
  _iwasawa_method_w->show();
  _table3_w->add( _iwasawa_method_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _iwasawa_method_w,
    "Select linear algebra method for Iwasawa factorization" );

  // basis_length
  _basis_length_w = new ::gtk::widget0::Entry( 128U );
  _basis_length_w->set_editable( true );
  _basis_length_w->show();
  _table3_w->add( _basis_length_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label33
  _label33_w = new ::gtk::widget0::Label( "Birkhoff" );
  _label33_w->set_alignment(0, 0.5);
  _label33_w->show();
  _table3_w->add( _label33_w, 0, 1, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label979
  _label979_w = new ::gtk::widget0::Label( "basislen" );
  _label979_w->set_alignment(0, 0.5);
  _label979_w->show();
  _table3_w->add( _label979_w, 0, 1, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // birkhoff
  _birkhoff_w = new ::gtk::widget0::ToggleButton(
    "enable", 0 );
  _birkhoff_w->show();
  _table3_w->add( _birkhoff_w, 1, 2, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _birkhoff_w,
    "Enable Birkhoff (r-Iwasawa) factorization" );

  // label1012
  _label1012_w = new ::gtk::widget0::Label( "Iwasawa" );
  _label1012_w->set_alignment(0, 0.5);
  _label1012_w->show();
  _table3_w->add( _label1012_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // one_column
  _one_column_w = new ::gtk::widget0::ToggleButton(
    "enable", 0 );
  _one_column_w->show();
  _table3_w->add( _one_column_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _one_column_w,
    "Enable one-column factorization. When enabled, the factorizor computes the first column of F and fills in the second column to make F unitary. When disabled, the factorizor computes both columns of F." );

  // label1016
  _label1016_w = new ::gtk::widget0::Label( "1 column" );
  _label1016_w->set_alignment(0, 0.5);
  _label1016_w->show();
  _table3_w->add( _label1016_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label3
  _label3_w = new ::gtk::widget0::Label( "Settings" );
  _label3_w->set_alignment(0, 0.5);
  _label3_w->show();
  _main_book_w->add_label( _label3_w );


}

Controls_::
~Controls_()
{
  delete _label3_w;
  delete _label1016_w;
  delete _one_column_w;
  delete _label1012_w;
  delete _birkhoff_w;
  delete _label979_w;
  delete _label33_w;
  delete _basis_length_w;
  delete _iwasawa_method_w;
  delete _table3_w;
  delete _frame11_w;
  delete _frame10_w;
  delete _integrator_count_w;
  delete _initial_integrator_count_w;
  delete _label980_w;
  delete _label32_w;
  delete _table2_w;
  delete _frame9_w;
  delete _polynomial_length_w;
  delete _label978_w;
  delete _table1_w;
  delete _frame8_w;
  delete _vbox6_w;
  delete _page3_w;
  delete _label2_w;
  delete _label1015_w;
  delete _lambda1_H3_w;
  delete _vbox58_w;
  delete _frame20_w;
  delete _lambda0_H3_w;
  delete _vbox57_w;
  delete _frame19_w;
  delete _reset_H3_w;
  delete _vbox56_w;
  delete _frame18_w;
  delete _label1013_w;
  delete _mean_curvature_w;
  delete _frame5_w;
  delete _normalshift_button2_w;
  delete _normalshift_button1_w;
  delete _normalshift_button0_w;
  delete _hbox5_w;
  delete _normalshift_w;
  delete _vbox5_w;
  delete _frame4_w;
  delete _lambda_button3_w;
  delete _lambda_button2_w;
  delete _lambda_button1_w;
  delete _lambda_button0_w;
  delete _hbox3_w;
  delete _lambda_R3_w;
  delete _vbox4_w;
  delete _frame3_w;
  delete _reset_R3_w;
  delete _vbox3_w;
  delete _frame100_w;
  delete _label1014_w;
  delete _lambda_button13_w;
  delete _lambda_button12_w;
  delete _lambda_button11_w;
  delete _lambda_button10_w;
  delete _hbox11_w;
  delete _lambda1_S3_w;
  delete _vbox55_w;
  delete _frame16_w;
  delete _lambda_button03_w;
  delete _lambda_button02_w;
  delete _lambda_button01_w;
  delete _lambda_button00_w;
  delete _hbox10_w;
  delete _lambda0_S3_w;
  delete _vbox54_w;
  delete _frame15_w;
  delete _reset_S3_w;
  delete _vbox53_w;
  delete _frame14_w;
  delete _parameter_notebook_w;
  delete _label1_w;
  delete _xstart_w;
  delete _scrolledwindow6_w;
  delete _frame101_w;
  delete _zstart_w;
  delete _frame1_w;
  delete _vbox50_w;
  delete _page1_w;
  delete _label0_w;
  delete _potential_w;
  delete _scrolledwindow5_w;
  delete _frame7_w;
  delete _potential_variable_w;
  delete _frame6_w;
  delete _vbox2_w;
  delete _page0_w;
  delete _main_book_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace cmclab

