/* GANG Software
 * VIEWER/isightui/gtk/Geometry_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Geometry_.H"

namespace isightui {
namespace gtk {


Geometry_::
Geometry_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::Frame( (char *)0 );
  _main_widget_w->show();

  // vbox15
  _vbox15_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox15_w->show();
  _main_widget_w->add( _vbox15_w );

  // hbox31
  _hbox31_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox31_w->show();
  _vbox15_w->add( _hbox31_w, false, true, 0 );

  // reset_position
  _reset_position_w = new ::gtk::widget0::ButtonCb<Geometry_>(
    "reset postion", this, &Geometry_::reset_position_cb );
  _reset_position_w->show();
  _hbox31_w->add( _reset_position_w, true, true, 0 );
  set_tooltip( _reset_position_w,
    "Restore the original position of surface in the view window" );

  // geometry_reset
  _geometry_reset_w = new ::gtk::widget0::ButtonCb<Geometry_>(
    "reset geom", this, &Geometry_::geometry_reset_cb );
  _geometry_reset_w->show();
  _hbox31_w->add( _geometry_reset_w, true, true, 0 );
  set_tooltip( _geometry_reset_w,
    "Reset the geometry and dimension" );

  // frame10
  _frame10_w = new ::gtk::widget0::Frame( "model" );
  _frame10_w->show();
  _vbox15_w->add( _frame10_w, false, true, 0 );

  // geometry_mode
  char const *geometry_mode_label[] = {
    "projective", "conformal", "Moebius" };

  _geometry_mode_w = new ::gtk::widget1::ButtonBarCb<Geometry_>(
    0U, geometry_mode_label, 1, 3, this, &Geometry_::geometry_mode_cb );

  _geometry_mode_w->show();
  _frame10_w->add( _geometry_mode_w );
  set_tooltip( _geometry_mode_w,
    "Geometry model of the ambient space" );

  // frame120
  _frame120_w = new ::gtk::widget0::Frame( "geometry" );
  _frame120_w->show();
  _vbox15_w->add( _frame120_w, false, true, 0 );

  // geometry_group
  char const *geometry_group_label[] = {
    "parabolic", "hyperbolic", "elliptic" };

  _geometry_group_w = new ::gtk::widget1::ButtonBarCb<Geometry_>(
    0U, geometry_group_label, 1, 3, this, &Geometry_::geometry_group_cb );

  _geometry_group_w->show();
  _frame120_w->add( _geometry_group_w );
  set_tooltip( _geometry_group_w,
    "Geometry of the ambient space" );

  // frame13
  _frame13_w = new ::gtk::widget0::Frame( "dimension" );
  _frame13_w->show();
  _vbox15_w->add( _frame13_w, false, true, 0 );

  // geometry_dim
  char const *geometry_dim_label[] = {
    "2", "3", "4" };

  _geometry_dim_w = new ::gtk::widget1::ButtonBarCb<Geometry_>(
    0U, geometry_dim_label, 1, 3, this, &Geometry_::geometry_dim_cb );

  _geometry_dim_w->show();
  _frame13_w->add( _geometry_dim_w );
  set_tooltip( _geometry_dim_w,
    "Dimension of the ambient space" );

  // frame121
  _frame121_w = new ::gtk::widget0::Frame( "mouse mode" );
  _frame121_w->show();
  _vbox15_w->add( _frame121_w, false, true, 0 );

  // mousemode
  char const *mousemode_label[] = {
    "rot/trans", "rotate", "translate", "invert", "scale" };

  _mousemode_w = new ::gtk::widget1::ButtonBarCb<Geometry_>(
    0U, mousemode_label, 1, 5, this, &Geometry_::mousemode_cb );

  _mousemode_w->show();
  _frame121_w->add( _mousemode_w );
  set_tooltip( _mousemode_w,
    "mouse bindings" );


}

Geometry_::
~Geometry_()
{
  delete _mousemode_w;
  delete _frame121_w;
  delete _geometry_dim_w;
  delete _frame13_w;
  delete _geometry_group_w;
  delete _frame120_w;
  delete _geometry_mode_w;
  delete _frame10_w;
  delete _geometry_reset_w;
  delete _reset_position_w;
  delete _hbox31_w;
  delete _vbox15_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace isightui

