/* GANG Software
 * VIEWER/isightui/gtk/GeomObject_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "GeomObject_.H"

namespace isightui {
namespace gtk {


GeomObject_::
GeomObject_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // vbox3
  _vbox3_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox3_w->show();

  // select_geomobject
  _select_geomobject_w = new ::gtk::widget1::CListCb<GeomObject_>(1U, this, &GeomObject_::select_geomobject_cb );

  _select_geomobject_w->show();
  _vbox3_w->add( _select_geomobject_w, true, true, 0 );
  set_tooltip( _select_geomobject_w,
    "List of geometry objects" );

  // table2
  _table2_w = new ::gtk::widget0::Table( 2, 2, true );
  _table2_w->show();
  _vbox3_w->add( _table2_w, false, true, 0 );

  // show_geomobject
  _show_geomobject_w = new ::gtk::widget0::ToggleButtonCb<GeomObject_>(
    "show", false, this, &GeomObject_::show_geomobject_cb );
  _show_geomobject_w->show();
  _table2_w->add( _show_geomobject_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _show_geomobject_w,
    "Show/hide the selected object" );

  // move_geomobject
  _move_geomobject_w = new ::gtk::widget0::ToggleButtonCb<GeomObject_>(
    "move", false, this, &GeomObject_::move_geomobject_cb );
  _move_geomobject_w->show();
  _table2_w->add( _move_geomobject_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _move_geomobject_w,
    "Enable motion for the selected object" );

  // replace_geomobject
  _replace_geomobject_w = new ::gtk::widget0::ToggleButton(
    "replace", false );
  _replace_geomobject_w->show();
  _table2_w->add( _replace_geomobject_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _replace_geomobject_w,
    "Toggle whether new objects replace old" );

  // delete_geomobject
  _delete_geomobject_w = new ::gtk::widget0::ButtonCb<GeomObject_>(
    "delete", this, &GeomObject_::delete_geomobject_cb );
  _delete_geomobject_w->show();
  _table2_w->add( _delete_geomobject_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _delete_geomobject_w,
    "Delete the selected object" );


}

GeomObject_::
~GeomObject_()
{
  delete _delete_geomobject_w;
  delete _replace_geomobject_w;
  delete _move_geomobject_w;
  delete _show_geomobject_w;
  delete _table2_w;
  delete _select_geomobject_w;
  delete _vbox3_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace isightui

