/* GANG Software
 * VIEWER/isightui/gtk/Shortcut_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Shortcut_.H"

namespace isightui {
namespace gtk {


Shortcut_::
Shortcut_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // hbox1
  _hbox1_w = new ::gtk::widget0::HBox( false, 0 );
  _hbox1_w->show();

  // label1
  _label1_w = new ::gtk::widget0::Label( "label1" );
  _label1_w->set_alignment(0.5, 0.5);
  _label1_w->show();
  _hbox1_w->add( _label1_w, false, false, 0 );

  // label2
  _label2_w = new ::gtk::widget0::Label( "label2" );
  _label2_w->set_alignment(0.5, 0.5);
  _label2_w->show();
  _hbox1_w->add( _label2_w, false, false, 0 );


}

Shortcut_::
~Shortcut_()
{
  delete _label2_w;
  delete _label1_w;
  delete _hbox1_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace isightui

