/* GANG Software
 * VIEWER/isightui/gtk/Style_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Style_.H"

namespace isightui {
namespace gtk {


Style_::
Style_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // vbox1
  _vbox1_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox1_w->show();

  // frame1
  _frame1_w = new ::gtk::widget0::Frame( "Style" );
  _frame1_w->show();
  _vbox1_w->add( _frame1_w, false, false, 0 );

  // table2
  _table2_w = new ::gtk::widget0::Table( 4, 2, true );
  _table2_w->show();
  _frame1_w->add( _table2_w );

  // style4
  _style4_w = new ::gtk::widget0::ButtonCb<Style_>(
    "transparent", this, &Style_::style4_cb );
  _style4_w->show();
  _table2_w->add( _style4_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style4_w,
    "Set the style of the surface to transparent" );

  // style5
  _style5_w = new ::gtk::widget0::ButtonCb<Style_>(
    "plain lit", this, &Style_::style5_cb );
  _style5_w->show();
  _table2_w->add( _style5_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style5_w,
    "Set the style of the surface to plain lit" );

  // style6
  _style6_w = new ::gtk::widget0::ButtonCb<Style_>(
    "plain unlit", this, &Style_::style6_cb );
  _style6_w->show();
  _table2_w->add( _style6_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style6_w,
    "Set the style of the surface to plain unlit" );

  // style1
  _style1_w = new ::gtk::widget0::ButtonCb<Style_>(
    "color by curvature", this, &Style_::style1_cb );
  _style1_w->show();
  _table2_w->add( _style1_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style1_w,
    "Color the surface by Gaussian curvature" );

  // style2
  _style2_w = new ::gtk::widget0::ButtonCb<Style_>(
    "flat", this, &Style_::style2_cb );
  _style2_w->show();
  _table2_w->add( _style2_w, 0, 1, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style2_w,
    "Set the surface material to flat" );

  // style3
  _style3_w = new ::gtk::widget0::ButtonCb<Style_>(
    "shiny", this, &Style_::style3_cb );
  _style3_w->show();
  _table2_w->add( _style3_w, 0, 1, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style3_w,
    "Set the surface material to shiny" );

  // style7
  _style7_w = new ::gtk::widget0::ButtonCb<Style_>(
    "wireframe", this, &Style_::style7_cb );
  _style7_w->show();
  _table2_w->add( _style7_w, 1, 2, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style7_w,
    "Set the style of the surface to wireframe" );

  // style0
  _style0_w = new ::gtk::widget0::ButtonCb<Style_>(
    "color by normal", this, &Style_::style0_cb );
  _style0_w->show();
  _table2_w->add( _style0_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _style0_w,
    "Color the surface by its normals" );

  // frame2
  _frame2_w = new ::gtk::widget0::Frame( "Window Objects" );
  _frame2_w->show();
  _vbox1_w->add( _frame2_w, false, false, 0 );

  // table1
  _table1_w = new ::gtk::widget0::Table( 2, 2, true );
  _table1_w->show();
  _frame2_w->add( _table1_w );

  // stars
  _stars_w = new ::gtk::widget0::ToggleButtonCb<Style_>(
    "stars", false, this, &Style_::stars_cb );
  _stars_w->show();
  _table1_w->add( _stars_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _stars_w,
    "toggle starry background" );

  // axes
  _axes_w = new ::gtk::widget0::ToggleButtonCb<Style_>(
    "axes", false, this, &Style_::axes_cb );
  _axes_w->show();
  _table1_w->add( _axes_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _axes_w,
    "toggle the coordinate axes" );

  // sphere
  _sphere_w = new ::gtk::widget0::ToggleButtonCb<Style_>(
    "sphere", false, this, &Style_::sphere_cb );
  _sphere_w->show();
  _table1_w->add( _sphere_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _sphere_w,
    "toggle the unit sphere" );


}

Style_::
~Style_()
{
  delete _sphere_w;
  delete _axes_w;
  delete _stars_w;
  delete _table1_w;
  delete _frame2_w;
  delete _style0_w;
  delete _style7_w;
  delete _style3_w;
  delete _style2_w;
  delete _style1_w;
  delete _style6_w;
  delete _style5_w;
  delete _style4_w;
  delete _table2_w;
  delete _frame1_w;
  delete _vbox1_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace isightui

