/* GANG Software
 * VIEWER/isightui/gtk/Window_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Window_.H"

namespace isightui {
namespace gtk {


Window_::
Window_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // vbox3
  _vbox3_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox3_w->show();

  // select_window
  _select_window_w = new ::gtk::widget1::CListCb<Window_>(1U, this, &Window_::select_window_cb );

  _select_window_w->show();
  _vbox3_w->add( _select_window_w, true, true, 0 );
  set_tooltip( _select_window_w,
    "List of windows" );

  // table1
  _table1_w = new ::gtk::widget0::Table( 1, 3, true );
  _table1_w->show();
  _vbox3_w->add( _table1_w, false, true, 0 );

  // delete_window
  _delete_window_w = new ::gtk::widget0::ButtonCb<Window_>(
    "delete", this, &Window_::delete_window_cb );
  _delete_window_w->show();
  _table1_w->add( _delete_window_w, 2, 3, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _delete_window_w,
    "Delete the selected window" );

  // new_window
  _new_window_w = new ::gtk::widget0::ButtonCb<Window_>(
    "new", this, &Window_::new_window_cb );
  _new_window_w->show();
  _table1_w->add( _new_window_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _new_window_w,
    "Open a new viewer window" );

  // show_window
  _show_window_w = new ::gtk::widget0::ToggleButtonCb<Window_>(
    "show", false, this, &Window_::show_window_cb );
  _show_window_w->show();
  _table1_w->add( _show_window_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _show_window_w,
    "Show/hide the selected window" );


}

Window_::
~Window_()
{
  delete _show_window_w;
  delete _new_window_w;
  delete _delete_window_w;
  delete _table1_w;
  delete _select_window_w;
  delete _vbox3_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace isightui

