/* GANG Software
 * VIEWER/isightui/gtk/Write_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Write_.H"

namespace isightui {
namespace gtk {


Write_::
Write_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // write
  _write_w = new ::gtk::widget1::FileCb<Write_>(
    this, &Write_::write_cb );

  _write_w->show();
  set_tooltip( _write_w,
    "Write file" );


}

Write_::
~Write_()
{
  delete _write_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace isightui

