/* GANG Software
 * LAB/bubbletonlab/gtk/Controls_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Controls_.H"

namespace bubbletonlab {
namespace gtk {


Controls_::
Controls_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // vbox1
  _vbox1_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox1_w->show();

  // frame1
  _frame1_w = new ::gtk::widget0::Frame( "centers" );
  _frame1_w->show();
  _vbox1_w->add( _frame1_w, true, true, 0 );

  // scrolledwindow2
  _scrolledwindow2_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow2_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow2_w->show();
  _frame1_w->add( _scrolledwindow2_w );

  // center
  _center_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _center_w->set_editable( true );
  _center_w->show();
  _scrolledwindow2_w->add( _center_w );

  // frame2
  _frame2_w = new ::gtk::widget0::Frame( "sizes" );
  _frame2_w->show();
  _vbox1_w->add( _frame2_w, true, true, 0 );

  // scrolledwindow3
  _scrolledwindow3_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow3_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow3_w->show();
  _frame2_w->add( _scrolledwindow3_w );

  // size
  _size_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _size_w->set_editable( true );
  _size_w->show();
  _scrolledwindow3_w->add( _size_w );

  // frame3
  _frame3_w = new ::gtk::widget0::Frame( "normal shift" );
  _frame3_w->show();
  _vbox1_w->add( _frame3_w, true, true, 0 );

  // vbox2
  _vbox2_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox2_w->show();
  _frame3_w->add( _vbox2_w );

  // normalshift
  numberwidget_config const normalshift_param = {
    "normal shift", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 1.0 };

  _normalshift_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &normalshift_param, this, &Controls_::normalshift_cb );

  _normalshift_w->show();
  _vbox2_w->add( _normalshift_w, false, true, 0 );
  set_tooltip( _normalshift_w,
    "Move through the normal-shifted family of surfaces" );

  // hbox1
  _hbox1_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox1_w->show();
  _vbox2_w->add( _hbox1_w, true, true, 0 );

  // normalshift_button0
  _normalshift_button0_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "CMC", this, &Controls_::normalshift_button0_cb );
  _normalshift_button0_w->show();
  _hbox1_w->add( _normalshift_button0_w, true, true, 0 );
  set_tooltip( _normalshift_button0_w,
    "Set the normal shift to 1 (default)" );

  // normalshift_button1
  _normalshift_button1_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "K", this, &Controls_::normalshift_button1_cb );
  _normalshift_button1_w->show();
  _hbox1_w->add( _normalshift_button1_w, true, true, 0 );
  set_tooltip( _normalshift_button1_w,
    "Set the normal shift to 0 to produce a K-surface (constant Gaussian curvature)" );

  // normalshift_button2
  _normalshift_button2_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "CMC", this, &Controls_::normalshift_button2_cb );
  _normalshift_button2_w->show();
  _hbox1_w->add( _normalshift_button2_w, true, true, 0 );
  set_tooltip( _normalshift_button2_w,
    "Set the normal shift to -1 to produce the parallel CMC surface" );


}

Controls_::
~Controls_()
{
  delete _normalshift_button2_w;
  delete _normalshift_button1_w;
  delete _normalshift_button0_w;
  delete _hbox1_w;
  delete _normalshift_w;
  delete _vbox2_w;
  delete _frame3_w;
  delete _size_w;
  delete _scrolledwindow3_w;
  delete _frame2_w;
  delete _center_w;
  delete _scrolledwindow2_w;
  delete _frame1_w;
  delete _vbox1_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace bubbletonlab

