/* GANG Software
 * LAB/minlab/gtk/Controls_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Controls_.H"

namespace minlab {
namespace gtk {


Controls_::
Controls_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget1::PopNotebook;
  _main_widget_w->set_tab_pos( GTK_POS_TOP );
  _main_widget_w->set_title( "MinLab | Controls" );
  _main_widget_w->set( 0 );
  _main_widget_w->show();
  set_tooltip( _main_widget_w,
    "Controls" );

  // page100
  _page100_w = new ::gtk::widget0::Frame( (char *)0 );
  _page100_w->show();
  _main_widget_w->add( _page100_w );

  // notebook_surf_data
  _notebook_surf_data_w = new ::gtk::widget1::PopNotebook;
  _notebook_surf_data_w->set_tab_pos( GTK_POS_TOP );
  _notebook_surf_data_w->set_title( "MinLab | Surface Data" );
  _notebook_surf_data_w->set( 0 );
  _notebook_surf_data_w->show();
  _page100_w->add( _notebook_surf_data_w );
  set_tooltip( _notebook_surf_data_w,
    "Surface Data" );

  // vbox23
  _vbox23_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox23_w->show();
  _notebook_surf_data_w->add( _vbox23_w );

  // frame1
  _frame1_w = new ::gtk::widget0::Frame( "z start" );
  _frame1_w->show();
  _vbox23_w->add( _frame1_w, false, false, 0 );

  // table1
  _table1_w = new ::gtk::widget0::Table( 1, 2, false );
  _table1_w->show();
  _frame1_w->add( _table1_w );

  // label2
  _label2_w = new ::gtk::widget0::Label( "z start" );
  _label2_w->set_alignment(0, 0.5);
  _label2_w->show();
  _table1_w->add( _label2_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // zstart_spinor
  _zstart_spinor_w = new ::gtk::widget0::Entry( 0U );
  _zstart_spinor_w->set_editable( true );
  _zstart_spinor_w->show();
  _table1_w->add( _zstart_spinor_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame7
  _frame7_w = new ::gtk::widget0::Frame( "spinor data" );
  _frame7_w->show();
  _vbox23_w->add( _frame7_w, false, false, 0 );

  // table101
  _table101_w = new ::gtk::widget0::Table( 2, 2, false );
  _table101_w->show();
  _frame7_w->add( _table101_w );

  // label1038
  _label1038_w = new ::gtk::widget0::Label( "spinor 1" );
  _label1038_w->set_alignment(0, 0.5);
  _label1038_w->show();
  _table101_w->add( _label1038_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // label1039
  _label1039_w = new ::gtk::widget0::Label( "spinor 2" );
  _label1039_w->set_alignment(0, 0.5);
  _label1039_w->show();
  _table101_w->add( _label1039_w, 0, 1, 1, 2,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // spinor1
  _spinor1_w = new ::gtk::widget0::Entry( 0U );
  _spinor1_w->set_editable( true );
  _spinor1_w->show();
  _table101_w->add( _spinor1_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // spinor2
  _spinor2_w = new ::gtk::widget0::Entry( 0U );
  _spinor2_w->set_editable( true );
  _spinor2_w->show();
  _table101_w->add( _spinor2_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame8
  _frame8_w = new ::gtk::widget0::Frame( "initial spinor data" );
  _frame8_w->show();
  _vbox23_w->add( _frame8_w, false, false, 0 );

  // table102
  _table102_w = new ::gtk::widget0::Table( 3, 2, false );
  _table102_w->show();
  _frame8_w->add( _table102_w );

  // label1040
  _label1040_w = new ::gtk::widget0::Label( "Xstart1" );
  _label1040_w->set_alignment(0, 0.5);
  _label1040_w->show();
  _table102_w->add( _label1040_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // label1041
  _label1041_w = new ::gtk::widget0::Label( "Xstart2" );
  _label1041_w->set_alignment(0, 0.5);
  _label1041_w->show();
  _table102_w->add( _label1041_w, 0, 1, 1, 2,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // spinor0_init
  _spinor0_init_w = new ::gtk::widget0::Entry( 0U );
  _spinor0_init_w->set_editable( true );
  _spinor0_init_w->show();
  _table102_w->add( _spinor0_init_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // spinor1_init
  _spinor1_init_w = new ::gtk::widget0::Entry( 0U );
  _spinor1_init_w->set_editable( true );
  _spinor1_init_w->show();
  _table102_w->add( _spinor1_init_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label1052
  _label1052_w = new ::gtk::widget0::Label( "Xstart3" );
  _label1052_w->set_alignment(0, 0.5);
  _label1052_w->show();
  _table102_w->add( _label1052_w, 0, 1, 2, 3,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // spinor2_init
  _spinor2_init_w = new ::gtk::widget0::Entry( 0U );
  _spinor2_init_w->set_editable( true );
  _spinor2_init_w->show();
  _table102_w->add( _spinor2_init_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label1042
  _label1042_w = new ::gtk::widget0::Label( "Spinor" );
  _label1042_w->set_alignment(0, 0.5);
  _label1042_w->show();
  _notebook_surf_data_w->add_label( _label1042_w );

  // vbox24
  _vbox24_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox24_w->show();
  _notebook_surf_data_w->add( _vbox24_w );

  // frame2
  _frame2_w = new ::gtk::widget0::Frame( "z start" );
  _frame2_w->show();
  _vbox24_w->add( _frame2_w, false, false, 0 );

  // table2
  _table2_w = new ::gtk::widget0::Table( 1, 2, false );
  _table2_w->show();
  _frame2_w->add( _table2_w );

  // label3
  _label3_w = new ::gtk::widget0::Label( "z start" );
  _label3_w->set_alignment(0, 0.5);
  _label3_w->show();
  _table2_w->add( _label3_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // zstart_weierstrass
  _zstart_weierstrass_w = new ::gtk::widget0::Entry( 0U );
  _zstart_weierstrass_w->set_editable( true );
  _zstart_weierstrass_w->show();
  _table2_w->add( _zstart_weierstrass_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame9
  _frame9_w = new ::gtk::widget0::Frame( "Weierstrass data" );
  _frame9_w->show();
  _vbox24_w->add( _frame9_w, false, false, 0 );

  // table103
  _table103_w = new ::gtk::widget0::Table( 2, 2, false );
  _table103_w->show();
  _frame9_w->add( _table103_w );

  // label1043
  _label1043_w = new ::gtk::widget0::Label( "g" );
  _label1043_w->set_alignment(0, 0.5);
  _label1043_w->show();
  _table103_w->add( _label1043_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // label1044
  _label1044_w = new ::gtk::widget0::Label( "f" );
  _label1044_w->set_alignment(0, 0.5);
  _label1044_w->show();
  _table103_w->add( _label1044_w, 0, 1, 1, 2,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // weierstrass1
  _weierstrass1_w = new ::gtk::widget0::Entry( 0U );
  _weierstrass1_w->set_editable( true );
  _weierstrass1_w->show();
  _table103_w->add( _weierstrass1_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // weierstrass2
  _weierstrass2_w = new ::gtk::widget0::Entry( 0U );
  _weierstrass2_w->set_editable( true );
  _weierstrass2_w->show();
  _table103_w->add( _weierstrass2_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame10
  _frame10_w = new ::gtk::widget0::Frame( "initial Weierstrass data" );
  _frame10_w->show();
  _vbox24_w->add( _frame10_w, false, false, 0 );

  // table104
  _table104_w = new ::gtk::widget0::Table( 3, 2, false );
  _table104_w->show();
  _frame10_w->add( _table104_w );

  // label1045
  _label1045_w = new ::gtk::widget0::Label( "Xstart1" );
  _label1045_w->set_alignment(0, 0.5);
  _label1045_w->show();
  _table104_w->add( _label1045_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // label1046
  _label1046_w = new ::gtk::widget0::Label( "Xstart2" );
  _label1046_w->set_alignment(0, 0.5);
  _label1046_w->show();
  _table104_w->add( _label1046_w, 0, 1, 1, 2,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // weierstrass0_init
  _weierstrass0_init_w = new ::gtk::widget0::Entry( 0U );
  _weierstrass0_init_w->set_editable( true );
  _weierstrass0_init_w->show();
  _table104_w->add( _weierstrass0_init_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // weierstrass1_init
  _weierstrass1_init_w = new ::gtk::widget0::Entry( 0U );
  _weierstrass1_init_w->set_editable( true );
  _weierstrass1_init_w->show();
  _table104_w->add( _weierstrass1_init_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label1053
  _label1053_w = new ::gtk::widget0::Label( "Xstart3" );
  _label1053_w->set_alignment(0, 0.5);
  _label1053_w->show();
  _table104_w->add( _label1053_w, 0, 1, 2, 3,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // weierstrass2_init
  _weierstrass2_init_w = new ::gtk::widget0::Entry( 0U );
  _weierstrass2_init_w->set_editable( true );
  _weierstrass2_init_w->show();
  _table104_w->add( _weierstrass2_init_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label1047
  _label1047_w = new ::gtk::widget0::Label( "Weierstrass" );
  _label1047_w->set_alignment(0, 0.5);
  _label1047_w->show();
  _notebook_surf_data_w->add_label( _label1047_w );

  // label100
  _label100_w = new ::gtk::widget0::Label( "Surface" );
  _label100_w->set_alignment(0, 0.5);
  _label100_w->show();
  _main_widget_w->add_label( _label100_w );

  // page101
  _page101_w = new ::gtk::widget0::Frame( (char *)0 );
  _page101_w->show();
  _main_widget_w->add( _page101_w );

  // vbox27
  _vbox27_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox27_w->show();
  _page101_w->add( _vbox27_w );

  // parameter_reset
  _parameter_reset_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "reset", this, &Controls_::parameter_reset_cb );
  _parameter_reset_w->show();
  _vbox27_w->add( _parameter_reset_w, false, false, 0 );
  set_tooltip( _parameter_reset_w,
    "Reset the associate family parameters to their default values" );

  // frame12
  _frame12_w = new ::gtk::widget0::Frame( "associate family" );
  _frame12_w->show();
  _vbox27_w->add( _frame12_w, true, true, 0 );

  // table110
  _table110_w = new ::gtk::widget0::Table( 2, 4, false );
  _table110_w->show();
  _frame12_w->add( _table110_w );

  // associate_slider
  numberwidget_config const associate_slider_param = {
    "assocate family", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.0 };

  _associate_slider_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &associate_slider_param, this, &Controls_::associate_slider_cb );

  _associate_slider_w->show();
  _table110_w->add( _associate_slider_w, 0, 4, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _associate_slider_w,
    "Move through the associate family of surfaces" );

  // associate_button0
  _associate_button0_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "1", this, &Controls_::associate_button0_cb );
  _associate_button0_w->show();
  _table110_w->add( _associate_button0_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _associate_button0_w,
    "Set the associate family parameter to 1 (the default value)" );

  // associate_button1
  _associate_button1_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "i", this, &Controls_::associate_button1_cb );
  _associate_button1_w->show();
  _table110_w->add( _associate_button1_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _associate_button1_w,
    "Set the associate family parameter to i" );

  // associate_button2
  _associate_button2_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-1", this, &Controls_::associate_button2_cb );
  _associate_button2_w->show();
  _table110_w->add( _associate_button2_w, 2, 3, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _associate_button2_w,
    "Set the associate family parameter to -1" );

  // associate_button3
  _associate_button3_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "-i", this, &Controls_::associate_button3_cb );
  _associate_button3_w->show();
  _table110_w->add( _associate_button3_w, 3, 4, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _associate_button3_w,
    "Set the associate family parameter to -i" );

  // label101
  _label101_w = new ::gtk::widget0::Label( "Param" );
  _label101_w->set_alignment(0, 0.5);
  _label101_w->show();
  _main_widget_w->add_label( _label101_w );

  // page102
  _page102_w = new ::gtk::widget0::Frame( (char *)0 );
  _page102_w->show();
  _main_widget_w->add( _page102_w );

  // table109
  _table109_w = new ::gtk::widget0::Table( 2, 1, false );
  _table109_w->show();
  _page102_w->add( _table109_w );

  // integrator_count
  numberwidget_config const integrator_count_param = {
    "integrator count", 0.0f, 1000000.0f, 0.02f, 0.14f, 1.0f, 0, 0.0f };

  _integrator_count_w = new ::gtk::widget1::NumberWidgetFloat(
    &integrator_count_param );

  _integrator_count_w->show();
  _table109_w->add( _integrator_count_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _integrator_count_w,
    "" );

  // initial_integrator_count
  numberwidget_config const initial_integrator_count_param = {
    "init integrator count", 0.0f, 1000000.0f, 0.02f, 0.14f, 1.0f, 0, 0.0f };

  _initial_integrator_count_w = new ::gtk::widget1::NumberWidgetFloat(
    &initial_integrator_count_param );

  _initial_integrator_count_w->show();
  _table109_w->add( _initial_integrator_count_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _initial_integrator_count_w,
    "" );

  // label102
  _label102_w = new ::gtk::widget0::Label( "Settings" );
  _label102_w->set_alignment(0, 0.5);
  _label102_w->show();
  _main_widget_w->add_label( _label102_w );


}

Controls_::
~Controls_()
{
  delete _label102_w;
  delete _initial_integrator_count_w;
  delete _integrator_count_w;
  delete _table109_w;
  delete _page102_w;
  delete _label101_w;
  delete _associate_button3_w;
  delete _associate_button2_w;
  delete _associate_button1_w;
  delete _associate_button0_w;
  delete _associate_slider_w;
  delete _table110_w;
  delete _frame12_w;
  delete _parameter_reset_w;
  delete _vbox27_w;
  delete _page101_w;
  delete _label100_w;
  delete _label1047_w;
  delete _weierstrass2_init_w;
  delete _label1053_w;
  delete _weierstrass1_init_w;
  delete _weierstrass0_init_w;
  delete _label1046_w;
  delete _label1045_w;
  delete _table104_w;
  delete _frame10_w;
  delete _weierstrass2_w;
  delete _weierstrass1_w;
  delete _label1044_w;
  delete _label1043_w;
  delete _table103_w;
  delete _frame9_w;
  delete _zstart_weierstrass_w;
  delete _label3_w;
  delete _table2_w;
  delete _frame2_w;
  delete _vbox24_w;
  delete _label1042_w;
  delete _spinor2_init_w;
  delete _label1052_w;
  delete _spinor1_init_w;
  delete _spinor0_init_w;
  delete _label1041_w;
  delete _label1040_w;
  delete _table102_w;
  delete _frame8_w;
  delete _spinor2_w;
  delete _spinor1_w;
  delete _label1039_w;
  delete _label1038_w;
  delete _table101_w;
  delete _frame7_w;
  delete _zstart_spinor_w;
  delete _label2_w;
  delete _table1_w;
  delete _frame1_w;
  delete _vbox23_w;
  delete _notebook_surf_data_w;
  delete _page100_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace minlab

