/* GANG Software
 * LAB/klab/gtk/Controls_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Controls_.H"

namespace klab {
namespace gtk {


Controls_::
Controls_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::VBox( false, 0 );
  _main_widget_w->show();

  // main_book
  _main_book_w = new ::gtk::widget1::PopNotebook;
  _main_book_w->set_tab_pos( GTK_POS_TOP );
  _main_book_w->set_title( "KLab | Controls" );
  _main_book_w->set( 0 );
  _main_book_w->show();
  _main_widget_w->add( _main_book_w, true, true, 0 );
  set_tooltip( _main_book_w,
    "Controls" );

  // page0
  _page0_w = new ::gtk::widget0::Frame( (char *)0 );
  _page0_w->show();
  _main_book_w->add( _page0_w );

  // vbox2
  _vbox2_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox2_w->show();
  _page0_w->add( _vbox2_w );

  // frame7
  _frame7_w = new ::gtk::widget0::Frame( "x potential" );
  _frame7_w->show();
  _vbox2_w->add( _frame7_w, true, true, 0 );

  // scrolledwindow5
  _scrolledwindow5_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow5_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow5_w->show();
  _frame7_w->add( _scrolledwindow5_w );

  // potential_x
  _potential_x_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _potential_x_w->set_editable( true );
  _potential_x_w->show();
  _scrolledwindow5_w->add( _potential_x_w );

  // frame102
  _frame102_w = new ::gtk::widget0::Frame( "y potential" );
  _frame102_w->show();
  _vbox2_w->add( _frame102_w, true, true, 0 );

  // scrolledwindow7
  _scrolledwindow7_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow7_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow7_w->show();
  _frame102_w->add( _scrolledwindow7_w );

  // potential_y
  _potential_y_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _potential_y_w->set_editable( true );
  _potential_y_w->show();
  _scrolledwindow7_w->add( _potential_y_w );

  // label0
  _label0_w = new ::gtk::widget0::Label( "Potential" );
  _label0_w->set_alignment(0, 0.5);
  _label0_w->show();
  _main_book_w->add_label( _label0_w );

  // page1
  _page1_w = new ::gtk::widget0::Frame( (char *)0 );
  _page1_w->show();
  _main_book_w->add( _page1_w );

  // vbox50
  _vbox50_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox50_w->show();
  _page1_w->add( _vbox50_w );

  // frame1
  _frame1_w = new ::gtk::widget0::Frame( "z start" );
  _frame1_w->show();
  _vbox50_w->add( _frame1_w, false, false, 0 );

  // zstart
  _zstart_w = new ::gtk::widget0::Entry( 0U );
  _zstart_w->set_editable( true );
  _zstart_w->show();
  _frame1_w->add( _zstart_w );

  // frame101
  _frame101_w = new ::gtk::widget0::Frame( "initial x" );
  _frame101_w->show();
  _vbox50_w->add( _frame101_w, true, true, 0 );

  // scrolledwindow8
  _scrolledwindow8_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow8_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow8_w->show();
  _frame101_w->add( _scrolledwindow8_w );

  // initial_x
  _initial_x_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _initial_x_w->set_editable( true );
  _initial_x_w->show();
  _scrolledwindow8_w->add( _initial_x_w );

  // frame103
  _frame103_w = new ::gtk::widget0::Frame( "initial y" );
  _frame103_w->show();
  _vbox50_w->add( _frame103_w, true, true, 0 );

  // scrolledwindow9
  _scrolledwindow9_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow9_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow9_w->show();
  _frame103_w->add( _scrolledwindow9_w );

  // initial_y
  _initial_y_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _initial_y_w->set_editable( true );
  _initial_y_w->show();
  _scrolledwindow9_w->add( _initial_y_w );

  // label1
  _label1_w = new ::gtk::widget0::Label( "Initial" );
  _label1_w->set_alignment(0, 0.5);
  _label1_w->show();
  _main_book_w->add_label( _label1_w );

  // frame14
  _frame14_w = new ::gtk::widget0::Frame( (char *)0 );
  _frame14_w->show();
  _main_book_w->add( _frame14_w );

  // vbox53
  _vbox53_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox53_w->show();
  _frame14_w->add( _vbox53_w );

  // reset_lambda
  _reset_lambda_w = new ::gtk::widget0::ButtonCb<Controls_>(
    "reset", this, &Controls_::reset_lambda_cb );
  _reset_lambda_w->show();
  _vbox53_w->add( _reset_lambda_w, false, false, 0 );
  set_tooltip( _reset_lambda_w,
    "Set the lambda parameter to 0" );

  // frame15
  _frame15_w = new ::gtk::widget0::Frame( "lambda1" );
  _frame15_w->show();
  _vbox53_w->add( _frame15_w, false, true, 0 );

  // vbox54
  _vbox54_w = new ::gtk::widget0::VBox( true, 0 );
  _vbox54_w->show();
  _frame15_w->add( _vbox54_w );

  // lambda
  numberwidget_config const lambda_param = {
    "lambda", -FLT_MAX, FLT_MAX, 0.00001, 0.0001, 0.01, 5, 0.0 };

  _lambda_w = new ::gtk::widget1::NumberWidgetFloatCb<Controls_>(
    &lambda_param, this, &Controls_::lambda_cb );

  _lambda_w->show();
  _vbox54_w->add( _lambda_w, false, true, 0 );
  set_tooltip( _lambda_w,
    "Move through the lambda family of surfaces." );

  // label2
  _label2_w = new ::gtk::widget0::Label( "Param" );
  _label2_w->set_alignment(0, 0.5);
  _label2_w->show();
  _main_book_w->add_label( _label2_w );

  // page3
  _page3_w = new ::gtk::widget0::Frame( (char *)0 );
  _page3_w->show();
  _main_book_w->add( _page3_w );

  // vbox6
  _vbox6_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox6_w->show();
  _page3_w->add( _vbox6_w );

  // frame8
  _frame8_w = new ::gtk::widget0::Frame( "loop" );
  _frame8_w->show();
  _vbox6_w->add( _frame8_w, true, true, 0 );

  // table1
  _table1_w = new ::gtk::widget0::Table( 1, 2, false );
  _table1_w->show();
  _frame8_w->add( _table1_w );

  // label978
  _label978_w = new ::gtk::widget0::Label( "polylen" );
  _label978_w->set_alignment(0, 0.5);
  _label978_w->show();
  _table1_w->add( _label978_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // polynomial_length
  _polynomial_length_w = new ::gtk::widget0::Entry( 128U );
  _polynomial_length_w->set_editable( true );
  _polynomial_length_w->show();
  _table1_w->add( _polynomial_length_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame9
  _frame9_w = new ::gtk::widget0::Frame( "integration" );
  _frame9_w->show();
  _vbox6_w->add( _frame9_w, true, true, 0 );

  // table2
  _table2_w = new ::gtk::widget0::Table( 2, 2, false );
  _table2_w->show();
  _frame9_w->add( _table2_w );

  // label32
  _label32_w = new ::gtk::widget0::Label( "step" );
  _label32_w->set_alignment(0, 0.5);
  _label32_w->show();
  _table2_w->add( _label32_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label980
  _label980_w = new ::gtk::widget0::Label( "init" );
  _label980_w->set_alignment(0, 0.5);
  _label980_w->show();
  _table2_w->add( _label980_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // initial_integrator_count
  _initial_integrator_count_w = new ::gtk::widget0::Entry( 128U );
  _initial_integrator_count_w->set_editable( true );
  _initial_integrator_count_w->show();
  _table2_w->add( _initial_integrator_count_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // integrator_count
  _integrator_count_w = new ::gtk::widget0::Entry( 128U );
  _integrator_count_w->set_editable( true );
  _integrator_count_w->show();
  _table2_w->add( _integrator_count_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label3
  _label3_w = new ::gtk::widget0::Label( "Setting" );
  _label3_w->set_alignment(0, 0.5);
  _label3_w->show();
  _main_book_w->add_label( _label3_w );


}

Controls_::
~Controls_()
{
  delete _label3_w;
  delete _integrator_count_w;
  delete _initial_integrator_count_w;
  delete _label980_w;
  delete _label32_w;
  delete _table2_w;
  delete _frame9_w;
  delete _polynomial_length_w;
  delete _label978_w;
  delete _table1_w;
  delete _frame8_w;
  delete _vbox6_w;
  delete _page3_w;
  delete _label2_w;
  delete _lambda_w;
  delete _vbox54_w;
  delete _frame15_w;
  delete _reset_lambda_w;
  delete _vbox53_w;
  delete _frame14_w;
  delete _label1_w;
  delete _initial_y_w;
  delete _scrolledwindow9_w;
  delete _frame103_w;
  delete _initial_x_w;
  delete _scrolledwindow8_w;
  delete _frame101_w;
  delete _zstart_w;
  delete _frame1_w;
  delete _vbox50_w;
  delete _page1_w;
  delete _label0_w;
  delete _potential_y_w;
  delete _scrolledwindow7_w;
  delete _frame102_w;
  delete _potential_x_w;
  delete _scrolledwindow5_w;
  delete _frame7_w;
  delete _vbox2_w;
  delete _page0_w;
  delete _main_book_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace klab

