/* GANG Software
 * LAB/lab/gtk/Compute_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Compute_.H"

namespace lab {
namespace gtk {


Compute_::
Compute_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::VBox( false, 0 );
  _main_widget_w->show();

  // table94
  _table94_w = new ::gtk::widget0::Table( 2, 2, true );
  _table94_w->show();
  _main_widget_w->add( _table94_w, false, false, 0 );

  // stop
  _stop_w = new ::gtk::widget0::ButtonCb<Compute_>(
    "stop", this, &Compute_::stop_cb );
  _stop_w->show();
  _table94_w->add( _stop_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _stop_w,
    "Halt computation" );

  // go
  _go_w = new ::gtk::widget0::ButtonCb<Compute_>(
    "go", this, &Compute_::go_cb );
  _go_w->show();
  _table94_w->add( _go_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _go_w,
    "Compute surface" );

  // progressbar
  _progressbar_w = new ::gtk::widget0::ProgressBar;
  _progressbar_w->show();
  _table94_w->add( _progressbar_w, 0, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // table20
  _table20_w = new ::gtk::widget0::Table( 2, 2, false );
  _table20_w->show();
  _main_widget_w->add( _table20_w, false, false, 0 );

  // label74
  _label74_w = new ::gtk::widget0::Label( "CPU time" );
  _label74_w->set_alignment(0, 0.5);
  _label74_w->show();
  _table20_w->add( _label74_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // label75
  _label75_w = new ::gtk::widget0::Label( "clock time" );
  _label75_w->set_alignment(0, 0.5);
  _label75_w->show();
  _table20_w->add( _label75_w, 0, 1, 1, 2,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // time0
  _time0_w = new ::gtk::widget0::Entry( 0U );
  _time0_w->set_editable( false );
  _time0_w->show();
  _table20_w->add( _time0_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // time1
  _time1_w = new ::gtk::widget0::Entry( 0U );
  _time1_w->set_editable( false );
  _time1_w->show();
  _table20_w->add( _time1_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame100
  _frame100_w = new ::gtk::widget0::Frame( "surface name" );
  _frame100_w->show();
  _main_widget_w->add( _frame100_w, false, false, 0 );

  // name
  _name_w = new ::gtk::widget0::Entry( 128U );
  _name_w->set_editable( true );
  _name_w->show();
  _frame100_w->add( _name_w );


}

Compute_::
~Compute_()
{
  delete _name_w;
  delete _frame100_w;
  delete _time1_w;
  delete _time0_w;
  delete _label75_w;
  delete _label74_w;
  delete _table20_w;
  delete _progressbar_w;
  delete _go_w;
  delete _stop_w;
  delete _table94_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace lab

