/* GANG Software
 * LAB/lab/gtk/Domain_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Domain_.H"

namespace lab {
namespace gtk {


Domain_::
Domain_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // domain_choice
  _domain_choice_w = new ::gtk::widget1::PopNotebook;
  _domain_choice_w->set_tab_pos( GTK_POS_TOP );
  _domain_choice_w->set_title( "Lab | Domain" );
  _domain_choice_w->set( 0 );
  _domain_choice_w->show();
  set_tooltip( _domain_choice_w,
    "Domain" );

  // table2
  _table2_w = new ::gtk::widget0::Table( 5, 2, false );
  _table2_w->show();
  _domain_choice_w->add( _table2_w );

  // rect_base
  _rect_base_w = new ::gtk::widget0::Entry( 128U );
  _rect_base_w->set_editable( true );
  _rect_base_w->show();
  _table2_w->add( _rect_base_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // rect_a0
  _rect_a0_w = new ::gtk::widget0::Entry( 128U );
  _rect_a0_w->set_editable( true );
  _rect_a0_w->show();
  _table2_w->add( _rect_a0_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // rect_count0
  _rect_count0_w = new ::gtk::widget0::Entry( 128U );
  _rect_count0_w->set_editable( true );
  _rect_count0_w->show();
  _table2_w->add( _rect_count0_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // rect_a1
  _rect_a1_w = new ::gtk::widget0::Entry( 128U );
  _rect_a1_w->set_editable( true );
  _rect_a1_w->show();
  _table2_w->add( _rect_a1_w, 1, 2, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // rect_count1
  _rect_count1_w = new ::gtk::widget0::Entry( 128U );
  _rect_count1_w->set_editable( true );
  _rect_count1_w->show();
  _table2_w->add( _rect_count1_w, 1, 2, 4, 5,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label6
  _label6_w = new ::gtk::widget0::Label( "O" );
  _label6_w->set_alignment(0, 0.5);
  _label6_w->show();
  _table2_w->add( _label6_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label8
  _label8_w = new ::gtk::widget0::Label( "A" );
  _label8_w->set_alignment(0, 0.5);
  _label8_w->show();
  _table2_w->add( _label8_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label9
  _label9_w = new ::gtk::widget0::Label( "M" );
  _label9_w->set_alignment(0, 0.5);
  _label9_w->show();
  _table2_w->add( _label9_w, 0, 1, 2, 3,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label10
  _label10_w = new ::gtk::widget0::Label( "B" );
  _label10_w->set_alignment(0, 0.5);
  _label10_w->show();
  _table2_w->add( _label10_w, 0, 1, 3, 4,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label11
  _label11_w = new ::gtk::widget0::Label( "N" );
  _label11_w->set_alignment(0, 0.5);
  _label11_w->show();
  _table2_w->add( _label11_w, 0, 1, 4, 5,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label12
  _label12_w = new ::gtk::widget0::Label( "Rect" );
  _label12_w->set_alignment(0, 0.5);
  _label12_w->show();
  _domain_choice_w->add_label( _label12_w );

  // table3
  _table3_w = new ::gtk::widget0::Table( 8, 2, false );
  _table3_w->show();
  _domain_choice_w->add( _table3_w );

  // polar_center
  _polar_center_w = new ::gtk::widget0::Entry( 0U );
  _polar_center_w->set_editable( true );
  _polar_center_w->show();
  _table3_w->add( _polar_center_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // polar_radius0
  _polar_radius0_w = new ::gtk::widget0::Entry( 0U );
  _polar_radius0_w->set_editable( true );
  _polar_radius0_w->show();
  _table3_w->add( _polar_radius0_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // polar_radius1
  _polar_radius1_w = new ::gtk::widget0::Entry( 0U );
  _polar_radius1_w->set_editable( true );
  _polar_radius1_w->show();
  _table3_w->add( _polar_radius1_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // polar_n_radius
  _polar_n_radius_w = new ::gtk::widget0::Entry( 0U );
  _polar_n_radius_w->set_editable( true );
  _polar_n_radius_w->show();
  _table3_w->add( _polar_n_radius_w, 1, 2, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // polar_angle0
  _polar_angle0_w = new ::gtk::widget0::Entry( 0U );
  _polar_angle0_w->set_editable( true );
  _polar_angle0_w->show();
  _table3_w->add( _polar_angle0_w, 1, 2, 4, 5,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // polar_angle1
  _polar_angle1_w = new ::gtk::widget0::Entry( 0U );
  _polar_angle1_w->set_editable( true );
  _polar_angle1_w->show();
  _table3_w->add( _polar_angle1_w, 1, 2, 5, 6,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // polar_n_angle
  _polar_n_angle_w = new ::gtk::widget0::Entry( 0U );
  _polar_n_angle_w->set_editable( true );
  _polar_n_angle_w->show();
  _table3_w->add( _polar_n_angle_w, 1, 2, 6, 7,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label14
  _label14_w = new ::gtk::widget0::Label( "O" );
  _label14_w->set_alignment(0, 0.5);
  _label14_w->show();
  _table3_w->add( _label14_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label15
  _label15_w = new ::gtk::widget0::Label( "R1" );
  _label15_w->set_alignment(0, 0.5);
  _label15_w->show();
  _table3_w->add( _label15_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label16
  _label16_w = new ::gtk::widget0::Label( "R2" );
  _label16_w->set_alignment(0, 0.5);
  _label16_w->show();
  _table3_w->add( _label16_w, 0, 1, 2, 3,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label17
  _label17_w = new ::gtk::widget0::Label( "M" );
  _label17_w->set_alignment(0, 0.5);
  _label17_w->show();
  _table3_w->add( _label17_w, 0, 1, 3, 4,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label18
  _label18_w = new ::gtk::widget0::Label( "A1" );
  _label18_w->set_alignment(0, 0.5);
  _label18_w->show();
  _table3_w->add( _label18_w, 0, 1, 4, 5,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label19
  _label19_w = new ::gtk::widget0::Label( "A2" );
  _label19_w->set_alignment(0, 0.5);
  _label19_w->show();
  _table3_w->add( _label19_w, 0, 1, 5, 6,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label20
  _label20_w = new ::gtk::widget0::Label( "N" );
  _label20_w->set_alignment(0, 0.5);
  _label20_w->show();
  _table3_w->add( _label20_w, 0, 1, 6, 7,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // table5
  _table5_w = new ::gtk::widget0::Table( 1, 2, false );
  _table5_w->show();
  _table3_w->add( _table5_w, 0, 2, 7, 8,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL), 0, 0 );

  // label21
  _label21_w = new ::gtk::widget0::Label( "radial growth" );
  _label21_w->set_alignment(0, 0.5);
  _label21_w->show();
  _table5_w->add( _label21_w, 0, 1, 0, 1,
    (GtkAttachOptions)0,
    (GtkAttachOptions)0, 0, 0 );

  // polar_mode
  char const *polar_mode_labels[] =
    { "linear", "exponential" };

  _polar_mode_w = new ::gtk::widget1::MenuButton(
    0, polar_mode_labels, 2 );
  _polar_mode_w->show();
  _table5_w->add( _polar_mode_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _polar_mode_w,
    "Select linear or exponential radial growth" );

  // label22
  _label22_w = new ::gtk::widget0::Label( "Polar" );
  _label22_w->set_alignment(0, 0.5);
  _label22_w->show();
  _domain_choice_w->add_label( _label22_w );

  // vbox1
  _vbox1_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox1_w->show();
  _domain_choice_w->add( _vbox1_w );

  // frame1
  _frame1_w = new ::gtk::widget0::Frame( "Boundary Specification" );
  _frame1_w->show();
  _vbox1_w->add( _frame1_w, true, true, 0 );

  // scrolledwindow1
  _scrolledwindow1_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow1_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  _scrolledwindow1_w->show();
  _frame1_w->add( _scrolledwindow1_w );

  // boundary_list
  _boundary_list_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _boundary_list_w->set_editable( true );
  _boundary_list_w->show();
  _scrolledwindow1_w->add( _boundary_list_w );

  // vbox2
  _vbox2_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox2_w->show();
  _vbox1_w->add( _vbox2_w, false, false, 0 );

  // hbox1
  _hbox1_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox1_w->show();
  _vbox2_w->add( _hbox1_w, false, false, 0 );

  // frame4
  _frame4_w = new ::gtk::widget0::Frame( "refine" );
  _frame4_w->show();
  _hbox1_w->add( _frame4_w, true, true, 0 );

  // refine
  _refine_w = new ::gtk::widget0::SpinButton(
    0.0, 0, 0.0, 1.0e6, 1.0, 1.0, 0 );
  _refine_w->show();
  _frame4_w->add( _refine_w );
  set_tooltip( _refine_w,
    "Select number of refinements of the triangulation" );

  // placeholder
  _placeholder_w = new ::gtk::widget0::Frame( (char *)0 );
  _placeholder_w->show();
  _hbox1_w->add( _placeholder_w, true, true, 0 );

  // hbox2
  _hbox2_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox2_w->show();
  _vbox2_w->add( _hbox2_w, false, false, 0 );

  // min_angle
  numberwidget_config const min_angle_param = {
    "min angle", 0.0, FLT_MAX, 0.001, 0.01, 0.1, 3, 0.0 };

  _min_angle_w = new ::gtk::widget1::NumberWidgetFloat(
    &min_angle_param );

  _min_angle_w->show();
  _hbox2_w->add( _min_angle_w, false, true, 0 );
  set_tooltip( _min_angle_w,
    "Constrain the triangle angles to a minimum value" );

  // max_area
  numberwidget_config const max_area_param = {
    "max area", 0.0, FLT_MAX, 0.001, 0.01, 0.1, 3, 0.0 };

  _max_area_w = new ::gtk::widget1::NumberWidgetFloat(
    &max_area_param );

  _max_area_w->show();
  _hbox2_w->add( _max_area_w, false, true, 0 );
  set_tooltip( _max_area_w,
    "Constrain the triangle areas to a maximum value" );

  // hbox3
  _hbox3_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox3_w->show();
  _vbox2_w->add( _hbox3_w, false, false, 0 );

  // max_area2
  numberwidget_config const max_area2_param = {
    "max area2", 0.0, FLT_MAX, 0.001, 0.01, 0.1, 3, 0.0 };

  _max_area2_w = new ::gtk::widget1::NumberWidgetFloat(
    &max_area2_param );

  _max_area2_w->show();
  _hbox3_w->add( _max_area2_w, false, true, 0 );
  set_tooltip( _max_area2_w,
    "Maximum area for refining" );

  // smooth
  numberwidget_config const smooth_param = {
    "smooth", 0.0, FLT_MAX, 0.02, 0.14, 1.0, 0, 0 };

  _smooth_w = new ::gtk::widget1::NumberWidgetFloat(
    &smooth_param );

  _smooth_w->show();
  _hbox3_w->add( _smooth_w, false, true, 0 );
  set_tooltip( _smooth_w,
    "Set the number of iterations for Laplacian smoothing of the triangulation" );

  // hbox4
  _hbox4_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox4_w->show();
  _vbox2_w->add( _hbox4_w, false, false, 0 );

  // curvature_exp
  numberwidget_config const curvature_exp_param = {
    "curvature exp", 0.0, FLT_MAX, 0.001, 0.01, 0.1, 3, 1.0 };

  _curvature_exp_w = new ::gtk::widget1::NumberWidgetFloat(
    &curvature_exp_param );

  _curvature_exp_w->show();
  _hbox4_w->add( _curvature_exp_w, false, true, 0 );
  set_tooltip( _curvature_exp_w,
    "Decay for curvature for pass 2" );

  // curvature_cut
  numberwidget_config const curvature_cut_param = {
    "curvature cut", 0.0, FLT_MAX, 0.001, 0.01, 0.1, 3, 1.0 };

  _curvature_cut_w = new ::gtk::widget1::NumberWidgetFloat(
    &curvature_cut_param );

  _curvature_cut_w->show();
  _hbox4_w->add( _curvature_cut_w, false, true, 0 );
  set_tooltip( _curvature_cut_w,
    "Cutoff for curvature for pass 2" );

  // label5
  _label5_w = new ::gtk::widget0::Label( "Triang" );
  _label5_w->set_alignment(0, 0.5);
  _label5_w->show();
  _domain_choice_w->add_label( _label5_w );

  // vbox3
  _vbox3_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox3_w->show();
  _domain_choice_w->add( _vbox3_w );

  // frame5
  _frame5_w = new ::gtk::widget0::Frame( "Curve Specification" );
  _frame5_w->show();
  _vbox3_w->add( _frame5_w, true, true, 0 );

  // scrolledwindow2
  _scrolledwindow2_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow2_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  _scrolledwindow2_w->show();
  _frame5_w->add( _scrolledwindow2_w );

  // curve_list
  _curve_list_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _curve_list_w->set_editable( true );
  _curve_list_w->show();
  _scrolledwindow2_w->add( _curve_list_w );

  // label26
  _label26_w = new ::gtk::widget0::Label( "Curve" );
  _label26_w->set_alignment(0.5, 0.5);
  _label26_w->show();
  _domain_choice_w->add_label( _label26_w );

  // table4
  _table4_w = new ::gtk::widget0::Table( 1, 2, false );
  _table4_w->show();
  _domain_choice_w->add( _table4_w );

  // domainfile
  _domainfile_w = new ::gtk::widget0::Entry( 128U );
  _domainfile_w->set_editable( true );
  _domainfile_w->show();
  _table4_w->add( _domainfile_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label24
  _label24_w = new ::gtk::widget0::Label( "file" );
  _label24_w->set_alignment(0, 0.5);
  _label24_w->show();
  _table4_w->add( _label24_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label25
  _label25_w = new ::gtk::widget0::Label( "File" );
  _label25_w->set_alignment(0, 0.5);
  _label25_w->show();
  _domain_choice_w->add_label( _label25_w );


}

Domain_::
~Domain_()
{
  delete _label25_w;
  delete _label24_w;
  delete _domainfile_w;
  delete _table4_w;
  delete _label26_w;
  delete _curve_list_w;
  delete _scrolledwindow2_w;
  delete _frame5_w;
  delete _vbox3_w;
  delete _label5_w;
  delete _curvature_cut_w;
  delete _curvature_exp_w;
  delete _hbox4_w;
  delete _smooth_w;
  delete _max_area2_w;
  delete _hbox3_w;
  delete _max_area_w;
  delete _min_angle_w;
  delete _hbox2_w;
  delete _placeholder_w;
  delete _refine_w;
  delete _frame4_w;
  delete _hbox1_w;
  delete _vbox2_w;
  delete _boundary_list_w;
  delete _scrolledwindow1_w;
  delete _frame1_w;
  delete _vbox1_w;
  delete _label22_w;
  delete _polar_mode_w;
  delete _label21_w;
  delete _table5_w;
  delete _label20_w;
  delete _label19_w;
  delete _label18_w;
  delete _label17_w;
  delete _label16_w;
  delete _label15_w;
  delete _label14_w;
  delete _polar_n_angle_w;
  delete _polar_angle1_w;
  delete _polar_angle0_w;
  delete _polar_n_radius_w;
  delete _polar_radius1_w;
  delete _polar_radius0_w;
  delete _polar_center_w;
  delete _table3_w;
  delete _label12_w;
  delete _label11_w;
  delete _label10_w;
  delete _label9_w;
  delete _label8_w;
  delete _label6_w;
  delete _rect_count1_w;
  delete _rect_a1_w;
  delete _rect_count0_w;
  delete _rect_a0_w;
  delete _rect_base_w;
  delete _table2_w;
  delete _domain_choice_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace lab

