/* GANG Software
 * LAB/lab/gtk/Sequence_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Sequence_.H"

namespace lab {
namespace gtk {


Sequence_::
Sequence_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // vbox1
  _vbox1_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox1_w->show();

  // hbox6
  _hbox6_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox6_w->show();
  _vbox1_w->add( _hbox6_w, false, false, 0 );

  // go
  _go_w = new ::gtk::widget0::ButtonCb<Sequence_>(
    "go", this, &Sequence_::go_cb );
  _go_w->show();
  _hbox6_w->add( _go_w, true, true, 0 );
  set_tooltip( _go_w,
    "Compute sequences of surfaces" );

  // go_write
  _go_write_w = new ::gtk::widget0::ButtonCb<Sequence_>(
    "go+write", this, &Sequence_::go_write_cb );
  _go_write_w->show();
  _hbox6_w->add( _go_write_w, true, true, 0 );
  set_tooltip( _go_write_w,
    "Compute sequences of surfaces and write image file" );

  // stop
  _stop_w = new ::gtk::widget0::ButtonCb<Sequence_>(
    "stop", this, &Sequence_::stop_cb );
  _stop_w->show();
  _hbox6_w->add( _stop_w, true, true, 0 );
  set_tooltip( _stop_w,
    "Stop the sequence computation" );

  // reset
  _reset_w = new ::gtk::widget0::ButtonCb<Sequence_>(
    "reset", this, &Sequence_::reset_cb );
  _reset_w->show();
  _hbox6_w->add( _reset_w, true, true, 0 );
  set_tooltip( _reset_w,
    "Compute sequences of surfaces" );

  // counter
  numberwidget_config const counter_param[] = {
    { "start", 0, 1.0e6f, 1.0f, 5.0f, 10.0f, 0, 0.0f },
    { "count",  0, 1.0e6f, 1.0f, 5.0f, 10.0f, 0, 0.0f } };

  _counter_w = new ::gtk::widget1::NumberWidget2Int(
    "seq counter", counter_param, 2 );

  _counter_w->show();
  _vbox1_w->add( _counter_w, false, true, 0 );
  set_tooltip( _counter_w,
    "Set the start value for the sequencer" );

  // hbox8
  _hbox8_w = new ::gtk::widget0::HBox( false, 0 );
  _hbox8_w->show();
  _vbox1_w->add( _hbox8_w, false, false, 0 );

  // label69
  _label69_w = new ::gtk::widget0::Label( "now" );
  _label69_w->set_alignment(0, 0.5);
  _label69_w->show();
  _hbox8_w->add( _label69_w, false, false, 0 );

  // now
  _now_w = new ::gtk::widget0::Entry( 0U );
  _now_w->set_editable( false );
  _now_w->show();
  _hbox8_w->add( _now_w, true, true, 0 );

  // table19
  _table19_w = new ::gtk::widget0::Table( 3, 2, false );
  _table19_w->show();
  _vbox1_w->add( _table19_w, false, false, 0 );

  // counter_varname
  _counter_varname_w = new ::gtk::widget0::Entry( 0U );
  _counter_varname_w->set_editable( true );
  _counter_varname_w->show();
  _table19_w->add( _counter_varname_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // time_varname
  _time_varname_w = new ::gtk::widget0::Entry( 0U );
  _time_varname_w->set_editable( true );
  _time_varname_w->show();
  _table19_w->add( _time_varname_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // function
  _function_w = new ::gtk::widget0::Entry( 0U );
  _function_w->set_editable( true );
  _function_w->show();
  _table19_w->add( _function_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label72
  _label72_w = new ::gtk::widget0::Label( "s varname" );
  _label72_w->set_alignment(0, 0.5);
  _label72_w->show();
  _table19_w->add( _label72_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label71
  _label71_w = new ::gtk::widget0::Label( "func s=f(n)" );
  _label71_w->set_alignment(0, 0.5);
  _label71_w->show();
  _table19_w->add( _label71_w, 0, 1, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label70
  _label70_w = new ::gtk::widget0::Label( "n varname" );
  _label70_w->set_alignment(0, 0.5);
  _label70_w->show();
  _table19_w->add( _label70_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // hbox7
  _hbox7_w = new ::gtk::widget0::HBox( false, 0 );
  _hbox7_w->show();
  _vbox1_w->add( _hbox7_w, false, false, 0 );

  // label73
  _label73_w = new ::gtk::widget0::Label( "filename" );
  _label73_w->set_alignment(0, 0.5);
  _label73_w->show();
  _hbox7_w->add( _label73_w, false, false, 0 );

  // filename
  _filename_w = new ::gtk::widget0::Entry( 0U );
  _filename_w->set_editable( true );
  _filename_w->show();
  _hbox7_w->add( _filename_w, true, true, 0 );


}

Sequence_::
~Sequence_()
{
  delete _filename_w;
  delete _label73_w;
  delete _hbox7_w;
  delete _label70_w;
  delete _label71_w;
  delete _label72_w;
  delete _function_w;
  delete _time_varname_w;
  delete _counter_varname_w;
  delete _table19_w;
  delete _now_w;
  delete _label69_w;
  delete _hbox8_w;
  delete _counter_w;
  delete _reset_w;
  delete _stop_w;
  delete _go_write_w;
  delete _go_w;
  delete _hbox6_w;
  delete _vbox1_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace lab

