/* GANG Software
 * GEOM/geomui/gtk/MeshClip_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "MeshClip_.H"

namespace geomui {
namespace gtk {


MeshClip_::
MeshClip_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::VBox( false, 0 );
  _main_widget_w->show();

  // hbox17
  _hbox17_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox17_w->show();
  _main_widget_w->add( _hbox17_w, false, false, 0 );

  // meshclip_reset
  _meshclip_reset_w = new ::gtk::widget0::ButtonCb<MeshClip_>(
    "reset", this, &MeshClip_::meshclip_reset_cb );
  _meshclip_reset_w->show();
  _hbox17_w->add( _meshclip_reset_w, true, true, 0 );
  set_tooltip( _meshclip_reset_w,
    "Reset mesh cliping" );

  // vbox37
  _vbox37_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox37_w->show();
  _main_widget_w->add( _vbox37_w, false, true, 0 );

  // frame14
  _frame14_w = new ::gtk::widget0::Frame( "i clipping" );
  _frame14_w->show();
  _vbox37_w->add( _frame14_w, false, true, 0 );

  // vbox38
  _vbox38_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox38_w->show();
  _frame14_w->add( _vbox38_w );

  // meshclip_i
  numberwidget_config const meshclip_i_param[] = {
    { "start", -1.0e6f, 1.0e6f, 0.02, 0.14, 1.0, 0, 0.0 },
    { "end", -1.0e6f, 1.0e6f, 0.02, 0.14, 1.0, 0, 0.0 } };

  _meshclip_i_w = new ::gtk::widget1::NumberWidget2IntCb<MeshClip_>(
    "mesh clip i", meshclip_i_param, 2, this, &MeshClip_::meshclip_cb );

  _meshclip_i_w->show();
  _vbox38_w->add( _meshclip_i_w, false, true, 0 );
  set_tooltip( _meshclip_i_w,
    "Set start of mesh clip in i direction" );

  // mesh_roll_i
  _mesh_roll_i_w = new ::gtk::widget0::HScaleFloatCb<MeshClip_>(
    0.0, 1.0, 0.01, 0.01, 3, 0.0, this, &MeshClip_::mesh_roll_cb );
  _mesh_roll_i_w->show();
  _vbox38_w->add( _mesh_roll_i_w, false, true, 0 );
  set_tooltip( _mesh_roll_i_w,
    "Roll the surface in the i direction" );

  // frame15
  _frame15_w = new ::gtk::widget0::Frame( "j clipping" );
  _frame15_w->show();
  _vbox37_w->add( _frame15_w, true, false, 0 );

  // vbox39
  _vbox39_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox39_w->show();
  _frame15_w->add( _vbox39_w );

  // meshclip_j
  numberwidget_config const meshclip_j_param[] = {
    { "start", -1.0e6f, 1.0e6f, 0.02, 0.14, 1.0, 0, 0.0 },
    { "end", -1.0e6f, 1.0e6f, 0.02, 0.14, 1.0, 0, 0.0 } };

  _meshclip_j_w = new ::gtk::widget1::NumberWidget2IntCb<MeshClip_>(
    "mesh clip j", meshclip_j_param, 2, this, &MeshClip_::meshclip_cb );

  _meshclip_j_w->show();
  _vbox39_w->add( _meshclip_j_w, false, true, 0 );
  set_tooltip( _meshclip_j_w,
    "Set start of mesh clip in j direction" );

  // mesh_roll_j
  _mesh_roll_j_w = new ::gtk::widget0::HScaleFloatCb<MeshClip_>(
    0.0, 1.0, 0.01, 0.01, 3, 0.0, this, &MeshClip_::mesh_roll_cb );
  _mesh_roll_j_w->show();
  _vbox39_w->add( _mesh_roll_j_w, false, true, 0 );
  set_tooltip( _mesh_roll_j_w,
    "Roll the surface in the j direction" );


}

MeshClip_::
~MeshClip_()
{
  delete _mesh_roll_j_w;
  delete _meshclip_j_w;
  delete _vbox39_w;
  delete _frame15_w;
  delete _mesh_roll_i_w;
  delete _meshclip_i_w;
  delete _vbox38_w;
  delete _frame14_w;
  delete _vbox37_w;
  delete _meshclip_reset_w;
  delete _hbox17_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace geomui

