/* GANG Software
 * GEOM/geomui/gtk/Statistics_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Statistics_.H"

namespace geomui {
namespace gtk {


Statistics_::
Statistics_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::VBox( false, 0 );
  _main_widget_w->show();

  // table6
  _table6_w = new ::gtk::widget0::Table( 4, 2, false );
  _table6_w->show();
  _main_widget_w->add( _table6_w, false, false, 0 );

  // label7
  _label7_w = new ::gtk::widget0::Label( "vertices" );
  _label7_w->set_alignment(0, 0.5);
  _label7_w->show();
  _table6_w->add( _label7_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label8
  _label8_w = new ::gtk::widget0::Label( "edges" );
  _label8_w->set_alignment(0, 0.5);
  _label8_w->show();
  _table6_w->add( _label8_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label9
  _label9_w = new ::gtk::widget0::Label( "faces" );
  _label9_w->set_alignment(0, 0.5);
  _label9_w->show();
  _table6_w->add( _label9_w, 0, 1, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label10
  _label10_w = new ::gtk::widget0::Label( "Euler" );
  _label10_w->set_alignment(0, 0.5);
  _label10_w->show();
  _table6_w->add( _label10_w, 0, 1, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // stat0
  _stat0_w = new ::gtk::widget0::Entry( 0U );
  _stat0_w->set_editable( false );
  _stat0_w->show();
  _table6_w->add( _stat0_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // stat1
  _stat1_w = new ::gtk::widget0::Entry( 0U );
  _stat1_w->set_editable( false );
  _stat1_w->show();
  _table6_w->add( _stat1_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // stat2
  _stat2_w = new ::gtk::widget0::Entry( 0U );
  _stat2_w->set_editable( false );
  _stat2_w->show();
  _table6_w->add( _stat2_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // stat3
  _stat3_w = new ::gtk::widget0::Entry( 0U );
  _stat3_w->set_editable( false );
  _stat3_w->show();
  _table6_w->add( _stat3_w, 1, 2, 3, 4,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );


}

Statistics_::
~Statistics_()
{
  delete _stat3_w;
  delete _stat2_w;
  delete _stat1_w;
  delete _stat0_w;
  delete _label10_w;
  delete _label9_w;
  delete _label8_w;
  delete _label7_w;
  delete _table6_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace geomui

