/* GANG Software
 * GEOM/milieu/gtk/ClipPlane_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "ClipPlane_.H"

namespace milieu {
namespace gtk {


ClipPlane_::
ClipPlane_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::Table( 2, 1, false );
  _main_widget_w->show();

  // id
  char const *id_label[] = {
    "1", "2", "3", "4", "5", "6" };

  _id_w = new ::gtk::widget1::ButtonBarCb<ClipPlane_>(
    0U, id_label, 1, 6, this, &ClipPlane_::id_cb );

  _id_w->show();
  _main_widget_w->add( _id_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _id_w,
    "Select a clipping plane" );

  // table109
  _table109_w = new ::gtk::widget0::Table( 3, 2, true );
  _table109_w->show();
  _main_widget_w->add( _table109_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)(GTK_FILL), 0, 0 );

  // enable
  _enable_w = new ::gtk::widget0::ToggleButtonCb<ClipPlane_>(
    "enable", 0, this, &ClipPlane_::enable_cb );
  _enable_w->show();
  _table109_w->add( _enable_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _enable_w,
    "Enable a clipping plane" );

  // attached
  _attached_w = new ::gtk::widget0::ToggleButtonCb<ClipPlane_>(
    "attach", 0, this, &ClipPlane_::attached_cb );
  _attached_w->show();
  _table109_w->add( _attached_w, 0, 1, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _attached_w,
    "Toggle whether this clipping plane moves with the geometry object" );

  // reset
  _reset_w = new ::gtk::widget0::ButtonCb<ClipPlane_>(
    "reset", this, &ClipPlane_::reset_cb );
  _reset_w->show();
  _table109_w->add( _reset_w, 0, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _reset_w,
    "Reset this clipping plane" );

  // moving
  _moving_w = new ::gtk::widget0::ToggleButtonCb<ClipPlane_>(
    "move", 0, this, &ClipPlane_::moving_cb );
  _moving_w->show();
  _table109_w->add( _moving_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _moving_w,
    "Move the clipping plane with the mouse" );

  // show
  _show_w = new ::gtk::widget0::ToggleButtonCb<ClipPlane_>(
    "show", 0, this, &ClipPlane_::show_cb );
  _show_w->show();
  _table109_w->add( _show_w, 1, 2, 2, 3,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _show_w,
    "Show the clipplane" );


}

ClipPlane_::
~ClipPlane_()
{
  delete _show_w;
  delete _moving_w;
  delete _reset_w;
  delete _attached_w;
  delete _enable_w;
  delete _table109_w;
  delete _id_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace milieu

