#!/bin/sh

# Set $BIN to the directory containing the bubbletonlab-gtk binary
BIN=/usr/local/bin

# Set $LIB to the directory containing the gang c libraries
LIB=/usr/local/lib

# Set BUBBLETONLAB_DOC to the URL containing BubbletonLab documentation
BUBBLETONLAB_DOC=http://www.gang.umass.edu/software/bubbletonlab/

# Set BUBBLETONLAB_LIB to a directory containing the library of BubbletonLab surface files.
BUBBLETONLAB_LIB=/usr/local/lib/BubbletonLab/surfaces

# Set ISIGHT_LIB to a directory containing the library of iSight surface files.
ISIGHT_LIB=/usr/local/lib/iSight/examples

# ------------------------------------

export BUBBLETONLAB_LIB BUBBLETONLAB_DOC
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB

CMD=bubbletonlab-gtk

case "$1" in
  -c)
    CMD=bubbletonlab-cmd
    shift
    ;;
esac

CMD=$BIN/$CMD

exec $CMD $@
