#!/bin/sh

# Set $BIN to the directory containing the cmclab-gtk binary
BIN=/usr/local/bin

# Set $LIB to the directory containing the gang c libraries
LIB=/usr/local/lib

# Set CMCLAB_DOC to the URL containing CMCLab documentation
CMCLAB_DOC=http://www.gang.umass.edu/software/cmclab/

# Set CMCLAB_LIB to a directory containing the library of CMCLab surface files.
CMCLAB_LIB=/usr/local/lib/CMCLab/surfaces

# Set ISIGHT_LIB to a directory containing the library of iSight surface files.
ISIGHT_LIB=/usr/local/lib/iSight/examples

# ------------------------------------

export CMCLAB_LIB CMCLAB_DOC
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB

CMD=cmclab-gtk

case "$1" in
  -c)
    CMD=cmclab-cmd
    shift
    ;;
esac

CMD=$BIN/$CMD

exec $CMD $@
