#!/bin/sh

# Set $BIN to the directory containing the klab-gtk binary
BIN=/usr/local/bin

# Set $LIB to the directory containing the gang c libraries
LIB=/usr/local/lib

# Set KLAB_DOC to the URL containing KLab documentation
KLAB_DOC=http://www.gang.umass.edu/software/klab/

# Set KLAB_LIB to a directory containing the library of KLab surface files.
KLAB_LIB=/usr/local/lib/KLab/surfaces

# Set ISIGHT_LIB to a directory containing the library of iSight surface files.
ISIGHT_LIB=/usr/local/lib/iSight/examples

# ------------------------------------

export KLAB_LIB KLAB_DOC
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB

CMD=klab-gtk

case "$1" in
  -c)
    CMD=klab-cmd
    shift
    ;;
esac

CMD=$BIN/$CMD

exec $CMD $@
