#!/bin/sh

# Set $BIN to the directory containing the minlab-gtk binary
BIN=/usr/local/bin

# Set $LIB to the directory containing the gang c libraries
LIB=/usr/local/lib

# Set MINLAB_DOC to the URL containing MinLab documentation
MINLAB_DOC=http://www.gang.umass.edu/software/minlab/

# Set MINLAB_LIB to a directory containing the library of MinLab surface files.
MINLAB_LIB=/usr/local/lib/MinLab/surfaces

# Set ISIGHT_LIB to a directory containing the library of iSight surface files.
ISIGHT_LIB=/usr/local/lib/iSight/examples

# ------------------------------------

export MINLAB_LIB MINLAB_DOC
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB

CMD=minlab-gtk

case "$1" in
  -c)
    CMD=minlab-cmd
    shift
    ;;
esac

CMD=$BIN/$CMD

exec $CMD $@
