#!/bin/sh

# Set $BIN to the directory containing the surflab-gtk binary
BIN=/usr/local/bin

# Set $LIB to the directory containing the gang c libraries
LIB=/usr/local/lib

# Set SURFLAB_DOC to the URL containing SurfLab documentation
SURFLAB_DOC=http://www.gang.umass.edu/software/surflab/

# Set SURFLAB_LIB to a directory containing the library of SurfLab surface files.
SURFLAB_LIB=/usr/local/lib/SurfLab/surfaces

# Set ISIGHT_LIB to a directory containing the library of iSight surface files.
ISIGHT_LIB=/usr/local/lib/iSight/examples

# ------------------------------------

export SURFLAB_LIB SURFLAB_DOC
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB

CMD=surflab-gtk

case "$1" in
  -c)
    CMD=surflab-cmd
    shift
    ;;
esac

CMD=$BIN/$CMD

exec $CMD $@
