/* GANG Software
 * WIDGET/app/gtk/About_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "About_.H"

namespace app {
namespace gtk {


About_::
About_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_vbox
  _main_vbox_w = new ::gtk::widget0::VBox( false, 0 );
  _main_vbox_w->show();

  // image
  _image_w = new ::gtk::widget0::VBox( false, 0 );
  _image_w->show();
  _main_vbox_w->add( _image_w, true, true, 0 );

  // label
  _label_w = new ::gtk::widget0::Label( "" );
  _label_w->set_alignment(0.5, 0.5);
  _label_w->show();
  _main_vbox_w->add( _label_w, false, false, 0 );


}

About_::
~About_()
{
  delete _label_w;
  delete _image_w;
  delete _main_vbox_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace app

