/* GANG Software
 * WIDGET/app/gtk/Message_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Message_.H"

namespace app {
namespace gtk {


Message_::
Message_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::VBox( false, 0 );
  _main_widget_w->show();

  // scrolledwindow1
  _scrolledwindow1_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow1_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow1_w->show();
  _main_widget_w->add( _scrolledwindow1_w, true, true, 0 );

  // messagebox
  _messagebox_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _messagebox_w->set_editable( false );
  _messagebox_w->show();
  _scrolledwindow1_w->add( _messagebox_w );

  // hbox1
  _hbox1_w = new ::gtk::widget0::HBox( true, 0 );
  _hbox1_w->show();
  _main_widget_w->add( _hbox1_w, false, false, 0 );

  // clear
  _clear_w = new ::gtk::widget0::ButtonCb<Message_>(
    "clear", this, &Message_::clear_cb );
  _clear_w->show();
  _hbox1_w->add( _clear_w, true, true, 0 );
  set_tooltip( _clear_w,
    "Clear message" );


}

Message_::
~Message_()
{
  delete _clear_w;
  delete _hbox1_w;
  delete _messagebox_w;
  delete _scrolledwindow1_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace app

