/* GANG Software
 * LAB/surflab/gtk/Controls_.C
 * Copyright (C) 2002 Nicholas Schmitt <nick@gang.umass.edu>
 * Wed Sep 18 16:39:46 2002
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
// Generated by glade++

#include "Controls_.H"

namespace surflab {
namespace gtk {


Controls_::
Controls_()
{
  _tooltips = new ::gtk::widget0::Tooltips;


  // main_widget
  _main_widget_w = new ::gtk::widget0::VBox( false, 0 );
  _main_widget_w->show();

  // frame1
  _frame1_w = new ::gtk::widget0::Frame( "domain variable names" );
  _frame1_w->show();
  _main_widget_w->add( _frame1_w, false, false, 0 );

  // table3
  _table3_w = new ::gtk::widget0::Table( 2, 2, false );
  _table3_w->show();
  _frame1_w->add( _table3_w );

  // var1
  _var1_w = new ::gtk::widget0::Entry( 0U );
  _var1_w->set_editable( true );
  _var1_w->show();
  _table3_w->add( _var1_w, 1, 2, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // var2
  _var2_w = new ::gtk::widget0::Entry( 0U );
  _var2_w->set_editable( true );
  _var2_w->show();
  _table3_w->add( _var2_w, 1, 2, 1, 2,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label1
  _label1_w = new ::gtk::widget0::Label( "var1" );
  _label1_w->set_alignment(0, 0.5);
  _label1_w->show();
  _table3_w->add( _label1_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // label2
  _label2_w = new ::gtk::widget0::Label( "var2" );
  _label2_w->set_alignment(0, 0.5);
  _label2_w->show();
  _table3_w->add( _label2_w, 0, 1, 1, 2,
    (GtkAttachOptions)(GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );

  // frame5
  _frame5_w = new ::gtk::widget0::Frame( "geometry" );
  _frame5_w->show();
  _main_widget_w->add( _frame5_w, false, false, 0 );

  // table9
  _table9_w = new ::gtk::widget0::Table( 1, 1, false );
  _table9_w->show();
  _frame5_w->add( _table9_w );

  // geometry
  char const *geometry_labels[] =
    { "parabolic", "hyperbolic", "elliptic" };

  _geometry_w = new ::gtk::widget1::MenuButtonCb<Controls_>(
    0, geometry_labels, 3, this, &Controls_::geometry_cb );
  _geometry_w->show();
  _table9_w->add( _geometry_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _geometry_w,
    "Geometry of the ambient space" );

  // frame3
  _frame3_w = new ::gtk::widget0::Frame( "dimension" );
  _frame3_w->show();
  _main_widget_w->add( _frame3_w, false, false, 0 );

  // table7
  _table7_w = new ::gtk::widget0::Table( 1, 1, false );
  _table7_w->show();
  _frame3_w->add( _table7_w );

  // dimension
  char const *dimension_labels[] =
    { "2", "3", "4" };

  _dimension_w = new ::gtk::widget1::MenuButtonCb<Controls_>(
    1, dimension_labels, 3, this, &Controls_::dimension_cb );
  _dimension_w->show();
  _table7_w->add( _dimension_w, 0, 1, 0, 1,
    (GtkAttachOptions)(GTK_EXPAND | GTK_FILL),
    (GtkAttachOptions)0, 0, 0 );
  set_tooltip( _dimension_w,
    "Dimension of the ambient space" );

  // frame2
  _frame2_w = new ::gtk::widget0::Frame( "surface parametrization" );
  _frame2_w->show();
  _main_widget_w->add( _frame2_w, true, true, 0 );

  // vbox1
  _vbox1_w = new ::gtk::widget0::VBox( false, 0 );
  _vbox1_w->show();
  _frame2_w->add( _vbox1_w );

  // function_box0
  _function_box0_w = new ::gtk::widget0::HBox( false, 0 );
  _function_box0_w->show();
  _vbox1_w->add( _function_box0_w, true, true, 0 );

  // label3
  _label3_w = new ::gtk::widget0::Label( "x1" );
  _label3_w->set_alignment(0.5, 0.5);
  _label3_w->show();
  _function_box0_w->add( _label3_w, false, false, 0 );

  // scrolledwindow1
  _scrolledwindow1_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow1_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow1_w->show();
  _function_box0_w->add( _scrolledwindow1_w, true, true, 0 );

  // function0
  _function0_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _function0_w->set_editable( true );
  _function0_w->show();
  _scrolledwindow1_w->add( _function0_w );

  // function_box1
  _function_box1_w = new ::gtk::widget0::HBox( false, 0 );
  _function_box1_w->show();
  _vbox1_w->add( _function_box1_w, true, true, 0 );

  // label4
  _label4_w = new ::gtk::widget0::Label( "x2" );
  _label4_w->set_alignment(0.5, 0.5);
  _label4_w->show();
  _function_box1_w->add( _label4_w, false, false, 0 );

  // scrolledwindow2
  _scrolledwindow2_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow2_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow2_w->show();
  _function_box1_w->add( _scrolledwindow2_w, true, true, 0 );

  // function1
  _function1_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _function1_w->set_editable( true );
  _function1_w->show();
  _scrolledwindow2_w->add( _function1_w );

  // function_box2
  _function_box2_w = new ::gtk::widget0::HBox( false, 0 );
  _function_box2_w->show();
  _vbox1_w->add( _function_box2_w, true, true, 0 );

  // label5
  _label5_w = new ::gtk::widget0::Label( "x3" );
  _label5_w->set_alignment(0.5, 0.5);
  _label5_w->show();
  _function_box2_w->add( _label5_w, false, false, 0 );

  // scrolledwindow3
  _scrolledwindow3_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow3_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow3_w->show();
  _function_box2_w->add( _scrolledwindow3_w, true, true, 0 );

  // function2
  _function2_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _function2_w->set_editable( true );
  _function2_w->show();
  _scrolledwindow3_w->add( _function2_w );

  // function_box3
  _function_box3_w = new ::gtk::widget0::HBox( false, 0 );
  _function_box3_w->show();
  _vbox1_w->add( _function_box3_w, true, true, 0 );

  // label6
  _label6_w = new ::gtk::widget0::Label( "x4" );
  _label6_w->set_alignment(0.5, 0.5);
  _label6_w->show();
  _function_box3_w->add( _label6_w, false, false, 0 );

  // scrolledwindow4
  _scrolledwindow4_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow4_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow4_w->show();
  _function_box3_w->add( _scrolledwindow4_w, true, true, 0 );

  // function3
  _function3_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _function3_w->set_editable( true );
  _function3_w->show();
  _scrolledwindow4_w->add( _function3_w );

  // function_box4
  _function_box4_w = new ::gtk::widget0::HBox( false, 0 );
  _function_box4_w->show();
  _vbox1_w->add( _function_box4_w, true, true, 0 );

  // label7
  _label7_w = new ::gtk::widget0::Label( "x5" );
  _label7_w->set_alignment(0.5, 0.5);
  _label7_w->show();
  _function_box4_w->add( _label7_w, false, false, 0 );

  // scrolledwindow5
  _scrolledwindow5_w = new ::gtk::widget0::ScrolledWindow( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _scrolledwindow5_w->set_policy(GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  _scrolledwindow5_w->show();
  _function_box4_w->add( _scrolledwindow5_w, true, true, 0 );

  // function4
  _function4_w = new ::gtk::widget0::Text( (GtkAdjustment *)0, (GtkAdjustment *)0 );
  _function4_w->set_editable( true );
  _function4_w->show();
  _scrolledwindow5_w->add( _function4_w );


}

Controls_::
~Controls_()
{
  delete _function4_w;
  delete _scrolledwindow5_w;
  delete _label7_w;
  delete _function_box4_w;
  delete _function3_w;
  delete _scrolledwindow4_w;
  delete _label6_w;
  delete _function_box3_w;
  delete _function2_w;
  delete _scrolledwindow3_w;
  delete _label5_w;
  delete _function_box2_w;
  delete _function1_w;
  delete _scrolledwindow2_w;
  delete _label4_w;
  delete _function_box1_w;
  delete _function0_w;
  delete _scrolledwindow1_w;
  delete _label3_w;
  delete _function_box0_w;
  delete _vbox1_w;
  delete _frame2_w;
  delete _dimension_w;
  delete _table7_w;
  delete _frame3_w;
  delete _geometry_w;
  delete _table9_w;
  delete _frame5_w;
  delete _label2_w;
  delete _label1_w;
  delete _var2_w;
  delete _var1_w;
  delete _table3_w;
  delete _frame1_w;
  delete _main_widget_w;

  delete _tooltips;
}

} // namespace gtk
} // namespace surflab

